### ISSUE TITLE
Infographic Design for Strategic Narrative 

### ISSUE THREAD

**Issue by LucyeoH** [mozilla/Community-Design#1]
Looking for someone to create an infographic for the strategic narrative. 

Project Brief - [here](https://docs.google.com/document/d/1Lx5XtZwxKBW_Gred2dhr2R0MN5jlmuj76BOwtqpNdjk/edit?usp=sharing)

Due Date: January 21st
Resource: [here](https://blog.mozilla.org/community/2016/01/06/mozillas-strategic-narrative-for-2016-and-beyond/)

**Comment by LucyeoH** [comment]
More info coming!

**Comment by elioqoshi** [comment]
Assigning to myself, thanks Lucy. @yofiesetiawan do you want to help here?

**Comment by yofiesetiawan** [comment]
@elioqoshi i don't think i'm good at this, i need to learn more... maybe next time.. Thanks Elio.. But i would love to keep follow the updates regarding this..

**Comment by elioqoshi** [comment]
@yofiesetiawan no worries!

@LucyeoH I am thinking to take such an approach to it:
http://elioqoshi.me/en/2015/06/oscal15-in-numbers/

**Comment by elioqoshi** [comment]
@LucyeoH Not sure if the doc you created helps much here. I'd need concrete numbers and sections to implement, otherwise I'd be spending time also on copywriting (to say the least) which isn't the focus here. If you could tell me in a more specific manner what to include, it would make it easier for me to avoid running in circles :)

**Comment by elioqoshi** [comment]
I might have interpreted it though. Is this the part I should focus on?

![infographic](https://cloud.githubusercontent.com/assets/5436686/12377086/895e25a2-bd10-11e5-982b-05abab5eb305.jpg)

**Comment by LucyeoH** [comment]
Hey @elioqoshi okay so I think it would be awesome if we could somehow make this an interactive graphic maybe rather than a typical "infographic". I made a mock-up to try and convey what I mean (please excuse it's hideous ugliness). Also it might be hard to read. I think we probably need to find an interactive designer for this too. 
![img_0450](https://cloud.githubusercontent.com/assets/8070833/12425104/42561e16-bea1-11e5-93a8-f1a483963db3.JPG)
![img_0451](https://cloud.githubusercontent.com/assets/8070833/12425105/4256607e-bea1-11e5-854e-d1168ee14662.JPG)
![img_0452](https://cloud.githubusercontent.com/assets/8070833/12425106/425c70f4-bea1-11e5-868b-b0dbb6ebabd8.JPG)

**Comment by elioqoshi** [comment]
uhm that would change things drastically @LucyeoH 
You'd want to go with an infographic first and then build from there. Wouldn't make sense to build a car from scratch when we can build a bike and steadily upgrade to a car when we are able to. Let's start with something more approachable (the OP request)

**Comment by flukeout** [comment]
Hey, here's a link to an infographics (of sorts) I did for Appmaker a while ago... maybe there are elements or something there someone can re-use...
https://dl.dropboxusercontent.com/u/109902/appmaker_inforgraphic.jpg

As far as the interactivity, I agree it changes the scope of the work significantly. It basically becomes a little website, and the specific type of interactions that you want really change the level of effort.

I agree with @elioqoshi with respect to doing a graphic first and working out some of the concepts and ideas in that format first. If it resonates with people then you could look at expanding the scope to include the ideas you've sketched above (which are really cool, btw)!

**Comment by LucyeoH** [comment]
Thanks @flukeout for your thoughts! @elioqoshi would be awesome if you could start with just the static version and we can look into interactivity after.

**Comment by elioqoshi** [comment]
@LucyeoH Okay, I can finish this by next week only then (travelling these days) will ping you next week

**Comment by LucyeoH** [comment]
@elioqoshi I think we're going to turn this into a mini-site so will take this off here for now as I agree that's more of a developer project. Thanks as always!
