### ISSUE TITLE
Mozilla Melbourne Sticker Design

### ISSUE THREAD

**Issue by pauljt** [mozilla/Community-Design#10]
I'm setting up a monthly meetup here in Melbourne to get people involved in Mozilla projects. Since there's actually a significant number of Mozillians in Melbourne now I'd like to get a sticker created so we are a 'real' Mozilla community! 

See bugs like: https://bugzilla.mozilla.org/show_bug.cgi?id=677850 & https://bugzilla.mozilla.org/show_bug.cgi?id=929143 for background.

Design ideas:
* Preferably circular like the [Taipei design](https://bug929143.bmoattachments.org/attachment.cgi?id=8345542)
* Needs iconic Melbourne things
  * Most likely motif is the green [Melbourne tram] (https://www.google.com.au/search?q=green+melbourne+tram&source=lnms&tbm=isch)
  * Maybe also [Flinders station] (http://www.australiaaa.com/wp-content/uploads/2014/06/melbourne3.jpg)

My idea was to basically just have a tram like [this one](https://c2.staticflickr.com/4/3596/3433843074_0e8af50ff8_b.jpg) and replace "CITY" with "MELBOURNE" and find a spot for the "mozilla spaces" text. Though technically its not a "Mozilla space" so might be better to limit the text to just "Mozilla Melbourne", similar to [existing community designs] (https://www.flickr.com/photos/mozillaindia/sets/72157626063609355/)

**Comment by pauljt** [comment]
PS I didn't mention it, but to be clear, this Melbourne, Australia I'm talking about here. I've a lot of love for *la belle province*, but we are not talking about [Melbourne, Quebec](https://en.wikipedia.org/wiki/Melbourne,_Quebec) or any other Melbournes outside Australia :)

**Comment by pauljt** [comment]
More design input (I'm only half joking here ;) 

<kamidphish>	pauljt: Logo needs more kangaroos with laser death rays
[10:27:54]  <pauljt>	kamidphish i agree. I was thinking a Mozilla Mechazilla riding a tram with laser/explosions/chaos/marsupials in the background
[10:28:10]  <kamidphish>	pauljt: Ship it!

**Comment by elioqoshi** [comment]
Thanks for the detailled request @pauljt !
I gave this a go, what do you think?

![sticker-01](https://cloud.githubusercontent.com/assets/5436686/12387526/773d7d06-bdcd-11e5-9f91-d72d1814a1ac.png)


Also, would appreciate your thoughts @mart3ll for this

**Comment by elioqoshi** [comment]
Here is one with a bit of stroke around the edge.
![sticker-01](https://cloud.githubusercontent.com/assets/5436686/12387620/1899e9e6-bdce-11e5-83ca-c048dfcb66d4.png)

**Comment by elioqoshi** [comment]
A preview to digest it a bit better 
![dribbble](https://cloud.githubusercontent.com/assets/5436686/12388483/70bb5f38-bdd3-11e5-973b-c6cdd847d55c.jpg)

**Comment by elioqoshi** [comment]
I did another variant with some grainy texture (taken from the Toronto sticker)
I quite like this one, what do you think?
![dirt-01](https://cloud.githubusercontent.com/assets/5436686/12390180/0bf34060-bdde-11e5-9127-6ae814b368d1.png)

**Comment by brianking** [comment]
Looks great. However I recommend not saying Spaces until there actually is a space there.

**Comment by elioqoshi** [comment]
thanks @briabking ! There seems to be, but it's not an official office space afaik. I can remove the space in case of doubt.

**Comment by pauljt** [comment]
For text lets go with "Mozilla" and Melbourne" since I guess technically this is a community sticker not a "mozilla space" sticker. (though we do have a space! Its just not very big or official ;)  I'll run it past the group and get some feedback.

Personally I think the design is on the right track* ;) I'm no designer so take all of this with a grain of salt. Just the first things that come to mind:
 - the tram feels a little flat, the texture helps a little maybe instead more detail/highlights on the tram detail? Or maybe  just a little more detail in the shapes, especially the windows?
 - The front-end tram graphic is pretty commonly used here (which is good) but I wonder if we can add a Mozilla element to it somehow (dino head, fox etc or something just to make it more Mozilla-ish)

Would you mind sharing the source/svg/whatever so I could experiment a little?

*hehe

**Comment by elioqoshi** [comment]
@pauljt Removed "Spaces" from the wordmark.

![grainynew-01](https://cloud.githubusercontent.com/assets/5436686/12405344/8ab52674-be43-11e5-95af-3a22a2118e4e.jpg)

- Let's keep it simple here. Adding too much details makes it noisy. The grain effect balances the minimalism style pretty well I'd say. Toronto uses the same effect in their stickers. In any case, I added a small detail to the windows.

- Tried adding a dino head or a fox, does not look good on such small space. I think the artwork should have more of its local community reflected than Mozilla branding (as with the other spaces stickers). The general style is similar to the other stickers in any case.

Here is the SVG:
http://elioqoshi.me/owncloud/index.php/s/6lqtPmHN2hW9rxe
Feel free to experiment with it and let me know how to proceed so we can wrap that up after getting some feedback from others.

**Comment by elioqoshi** [comment]
@pauljt could you run this through some feedback so we can wrap this up?

**Comment by elioqoshi** [comment]
@pauljt could you run this through some feedback so we can wrap this up?

**Comment by pauljt** [comment]
Sorry - I swear I replied to this, but I guess I didn't hit submit or something. This is great Elio, I'm going to have a play on the weekend, but I think we'll just go with this as is. Thanks again for the quick turnaround.

**Comment by mart3ll** [comment]
Hey all, please let me check with Tim and Mary Ellen around this one before it goes any further. I wouldn't want this to start being used before they've had a chance to have input on this. We'll need to discuss which of these community design projects need Marketing approval before they're finalized. Thanks!

**Comment by brianking** [comment]
@mart3ll if we could define some lightweight process for approval, such as copying someone here in github, that would be ideal. The current BZ process seems kind of heavy.

**Comment by pauljt** [comment]
Sure thing - please get back to me asap though as I have a speaking engagement on the 11th of Feb, and I was hoping to get some stickers made up before then.

**Comment by mart3ll** [comment]
Yes, Tim is looking into having a meeting to see what we can set up. 

We'll sort out a meeting time and go over what can be set up for some brand guidelines and approvals. 

Thanks!

**Comment by elioqoshi** [comment]
Thanks @mart3ll for the headsup! As @brianking said, this is something we might need to look into for the future to lower friction of contributions.

**Comment by marcoscaceres** [comment]
Design looks great BTW :+1:

**Comment by pauljt** [comment]
@mart3ll ping?? Any update to share here?

**Comment by elioqoshi** [comment]
@pauljt @mart3ll let me know how to proceed with this :)
