### ISSUE TITLE
Mozilla Security Logo & T-Shirt

### ISSUE THREAD

**Issue by pauljt** [mozilla/Community-Design#11]
This isn't a high priority, but I've been talking with a few folks about getting new "securing mozilla" t-shirts for security contributors (e.g. security teams, bounty recipients, gear for security confs etc). The existing logo was https://wiki.mozilla.org/File:OpSec.png which I actually like since its mostly not a security cliche (no padlocks, shields, chains, keys etc). But its a little tired and it would be cool to see what the community could come up with. 

Thoughts?

**Comment by elioqoshi** [comment]
First proposal ready. Let me know what you think of the direction :)

![draft-01](https://cloud.githubusercontent.com/assets/5436686/12391762/5262b254-bdea-11e5-8fa0-1f8ad8e2e708.jpg)

**Comment by mozfreddyb** [comment]
I like the direction where this is going!
Personally not a big fan of the badge (right version).

**Comment by elioqoshi** [comment]
Not fond of the badge variants either @mozfreddyb 
I will explore the left variant further

**Comment by elioqoshi** [comment]
Another variant

![draft2](https://cloud.githubusercontent.com/assets/5436686/12404176/7f0e5228-be39-11e5-962d-8ec60d5c18f1.jpg)

**Comment by jeffbryner** [comment]
+1 for the dotted M  (without arrows). Looks good with black or white background

**Comment by gdestuynder** [comment]
+1 for dotted M as well.

I wonder if the font for Security could be a little closer to the Mozilla font (i dont know the technical terms, but I would think a little less rounded). Feel free to disregard my suggestion though, it's not a strong opinion ;-)

Another thing I liked in the old logo are the 0's and 1's, always wanted to keep but change them to have a hidden message in them, since, security and all (my github avatar is in fact the old logo)

**Comment by jvehent** [comment]
> Another thing I liked in the old logo are the 0's and 1's, always wanted to keep but change them to have a hidden message in them, since, security and all (my github avatar is in fact the old logo)

I was just going to write the same thing, so definitely :+1: 
For example:
```
01010110 01100001 01110001 01110110 01101001 01110110 01110001 01101000 01101110 01111001 01100110 10000000011001 00100000 01100110 01110010 01110000 01101000 01100101 01110110 01100111 01101100 00100000 01101110 01100001 01110001 00100000 01100011 01100101 01110110 01101001 01101110 01110000 01101100 00100000 01100010 01100001 00100000 01100111 01110101 01110010 00100000 01010110 01100001 01100111 01110010 01100101 01100001 01110010 01100111 00100000 01101110 01100101 01110010 00100000 01110011 01101000 01100001 01110001 01101110 01111010 01110010 01100001 01100111 01101110 01111001 00100000 01101110 01100001 01110001 00100000 01111010 01101000 01100110 01100111 00100000 01100001 01100010 01100111 00100000 01101111 01110010 00100000 01100111 01100101 01110010 01101110 01100111 01110010 01110001 00100000 01101110 01100110 00100000 01100010 01100011 01100111 01110110 01100010 01100001 01101110 01111001 00101110 
```
Which is Mozilla Manifesto principle #4, "encrypted" with ROT13 (a recurrent security joke), and converted from ascii to binary. That ought to do it :)

**Comment by elioqoshi** [comment]
Thanks for the feedback guys!
@gdestuynder I've used the Meta font, which is the same font used for the mozilla wordmark, so they're the same. Firefox uses the exact same font weight also for this, so this is standard and not something I've invented.

Regarding the binary code: Let's keep it simple, adding 0's and 1's to a logo hardly works. If you want an artwork for a TShirt though, that's a different thing where we can try that out (although I think the logo speaks well for itself as of now).

**Comment by mpurzynski** [comment]
The dotten M, first variant (thinner) is spectacular! Let's go with it.

Badges and coded hidden messages are to be avoided, like every other cliche Paul described. Let's have something no one does :-)

**Comment by elioqoshi** [comment]
I agree with @mpurzynski 
Let me know if I should export the final files for you guys

**Comment by mozfreddyb** [comment]
This seems like a great logo for our own security peeps!

How can we make it fit better for outside contributors, like folks who've won a bug bounty by finding security issues in Mozilla products?
I think the wording on the previous t-shirts ("*Securing Mozilla*") supported that case much better.

**Comment by elioqoshi** [comment]
@mozfreddyb Well, that would go under artwork. As I said, once we finalize the logo, we can easily make derivatives for artwork.

In that case, I'd go with something like this:
![securing mozilla](https://cloud.githubusercontent.com/assets/5436686/12447824/5b661a74-bf72-11e5-8644-7ecf16691756.jpg)

**Comment by mozfreddyb** [comment]
:+1:

**Comment by elioqoshi** [comment]
I will export these here so we can wrap it up. Anyone from you able to push the final files to our repo? Not a great git user! :blush:

**Comment by mozfreddyb** [comment]
I can make a pull request.
I suggest you send me a ZIP of a folder that I can place placed alongside the `FSA` directory in this repo.

**Comment by elioqoshi** [comment]
@mozfreddyb 

Here we go:
http://elioqoshi.me/owncloud/index.php/s/rl0zn7pqQ4XiwQw

I'd love to! I will be travelling to Singapore tomorrow but I will ping you, thanks!

**Comment by gdestuynder** [comment]
thanks for your work on this :)
