### ISSUE TITLE
Mozilla Running Club Logo

### ISSUE THREAD

**Issue by davehunt** [mozilla/Community-Design#12]
It would be great to have a logo for Mozillians that love to run. We have a [Strava club](https://www.strava.com/clubs/mozilla) and a [mailing list](https://groups.google.com/a/mozilla.com/forum/#!members/running), and we run together whenever we can. This logo would be used for stickers and would also hopefully be printed on high quality running shirts.

**Comment by elioqoshi** [comment]
Hey @davehunt Thanks for filing this issue! Will give this some attention today

**Comment by elioqoshi** [comment]
First proposal, let me know what you think :)

![draft-01](https://cloud.githubusercontent.com/assets/5436686/12390924/68d2a432-bde4-11e5-8e7d-60ba2dbdf5c6.jpg)

**Comment by Raphseck** [comment]
Great. :)
love the blue.

**Comment by davehunt** [comment]
Wow @elioqoshi that was fast! I've love to see if there are any other ideas from the community. Is it okay for us to leave this open for a while and see if we get any other designs? :smile:

**Comment by tarekziade** [comment]
Neat!   Would it be hard to have a fox tail hanging behind the shoe ? ;)

**Comment by elioqoshi** [comment]
Sure! Will do another revision and we can keep this open for another designer to chime in :)

**Comment by seeam** [comment]
I am not good at logo design but still tried some different version. What do you think?
![mozilla-running-club-logo](https://cloud.githubusercontent.com/assets/7550283/12399629/63383ada-be45-11e5-8d29-111269c924e7.jpg)

**Comment by elioqoshi** [comment]
thank you @seeam ! These look good! Usually we use Meta or Fira Sans (Regular Italic here) just so you know :)

**Comment by seeam** [comment]
Hi @elioqoshi thanks for your appreciation. And I have used Fira Sans OT (Regular Italic). Is there any difference between OT and TTF?

**Comment by elioqoshi** [comment]
Ah I see, I used Meta.
You can try reducing the distance between the letters for better results in this case :)

**Comment by seeam** [comment]
So here is another version with little tracking change, also increased the font size. What do you think now @elioqoshi ?
![mozilla-running-club-logo-v2](https://cloud.githubusercontent.com/assets/7550283/12400675/afa311e6-be4b-11e5-8821-6d449494a6fb.jpg)

**Comment by elioqoshi** [comment]
Better! Thanks for chiming in!

**Comment by elioqoshi** [comment]
The same proposal with a Firefox Tail

![draft-01](https://cloud.githubusercontent.com/assets/5436686/12403918/b09114fe-be37-11e5-94ff-21bd87b9a371.jpg)

**Comment by elioqoshi** [comment]
@davehunt run the proposals through your fellow runners so we can go ahead with this :)

**Comment by jenpez** [comment]
Hope it's not too late to submit a logo idea...
![mozillarunningclub](https://cloud.githubusercontent.com/assets/16767717/12470214/6ab63efc-bfc0-11e5-8bf0-4b4df278358e.jpg)

**Comment by jmaher** [comment]
I like the blue!  The shoe is slick (not a fan of the version with a tail), I like the runner as well.  It is really cool to see great ideas.

**Comment by cstipkovic** [comment]
:+1:

**Comment by whimboo** [comment]
My favorite is definitely the runner! IMHO it's an eye catcher people would remember, especially on a printed shirt. The only thing is that we as runners would also have to appear that athletic! :)

**Comment by cassiemc** [comment]
Not sure if your running club is just men but could potentially be an issue with @jenpez's design.

**Comment by kmoir** [comment]
I agree, the running group is not all men

**Comment by jenpez** [comment]
Added a woman runner to balance it out.
![mozillarunningclub](https://cloud.githubusercontent.com/assets/16767717/12499699/d493d540-c07a-11e5-9679-4651833796a9.jpg)

**Comment by yofiesetiawan** [comment]
@jenpez That's quite badass! But instead of becoming logo, this one looks far better for huge print ad...

**Comment by 3r1ccc** [comment]
Like the the badge with sneaker, would it look good in orange design?

**Comment by rwood-moz** [comment]
All really cool designs! My personal favourite is the top-left one in the latest set by @seeam Simple but attractive and love the Firefox orange

**Comment by pelmers** [comment]
For a shirt, I like @seeam revised designs most.

**Comment by jenpez** [comment]
Reworked the logo, more graphic, a little less complicated.
![mozillarunningclub2](https://cloud.githubusercontent.com/assets/16767717/12581726/7c937a64-c406-11e5-9313-5f880be75b4d.jpg)

**Comment by tarekziade** [comment]
oh wow I really like that last one <3

**Comment by cstipkovic** [comment]
@jenpez, really cool :+1:

**Comment by elioqoshi** [comment]
Thanks @jenpez for the proposals :)
The artwork looks really great! However they are quite heavy on the eye for a logo. It would be great to have these runners for artwork, but a logo should be simple and conceptual in our case, I'd suggest.

My 5 cents :)

**Comment by elioqoshi** [comment]
Further, there is a certain guideline of how symbols should be placed in a logo (in our case, the icon is always in the left of the wordmark). For consistency reasons, we should respect that.

@davehunt what's your input?

**Comment by davehunt** [comment]
All of the designs are great, but I do particularly like @jenpez latest version and can see if being used on a running shirt. I think the other designs would perhaps work better as a team avatar or as stickers. I wasn't aware of the wordmark guidelines, but that makes sense.

I also think @jenpez design could be tweaked for different purposes - for example we could have the two runners together, or perhaps it would be cool to let people choose which runner they want on their shirt.

My vote would be for @seeam's orange logo (I prefer the one on the left) to be used as an avatar without the wordmark and for stickers with the wordmark. For the running shirt I'd love to see @jenpez design on the back maybe without the wordmark, and with @seeam design on the front with the wordmark? I think the two would go well together.

**Comment by whimboo** [comment]
I can second all what Dave said. I feel the same.

**Comment by tarekziade** [comment]
I second Dave comments as well. I also think that @seeam design would fit great on the right shirtsleeve, where we usually put "mozilla" in some of our t-shirts

**Comment by davehunt** [comment]
This is what I was thinking:
![img_8718](https://cloud.githubusercontent.com/assets/122800/12755521/bc0370c0-c9c7-11e5-9533-f3f1ae282263.jpg)

@tarekziade do you think you could get back in touch with the running shirt company you were previously talking to about printing this design? I think it would look best printed on a blue shirt to match the orange/blue from the Firefox logo, but it would probably work well on other colours.

I guess all we'll need then is the various graphics in the appropriate formats. Perhaps @elioqoshi can help in identifying what we'd need?

**Comment by tarekziade** [comment]
@davehunt I sent an e-mail and pointed them that issue.

to get a price from them, we need to decide how many shirts we want and the various sizes. Maybe a pad is easier for this

**Comment by tarekziade** [comment]
For reference this is the shirt we're thinking about https://www.owayo.com/running-custom-short-sleeve-shirts.htm

One thing I should mentioned is that IIRC they raised their prices on that shirt. So that could be a bit expensive.  That said, I was able to try samples and they are good fabric.

here are a few pics of me wearing the shirt 2 years ago:

- wearing an american apparel Small so you can compare : http://ziade.org/shirt/shirt%20%281%20of%205%29.jpg  (I look depressed on this one but I am not)  :)
- The owayo Small Men: http://ziade.org/shirt/shirt%20%282%20of%205%29.jpg  (I look happier now!)
- The back : http://ziade.org/shirt/shirt%20%283%20of%205%29.jpg (notice how the shirt is longer on the back)
- The side : http://ziade.org/shirt/shirt%20%284%20of%205%29.jpg
- Fabric detail: http://ziade.org/shirt/shirt%20%285%20of%205%29.jpg (the brand logo is not too big)

**Comment by tarekziade** [comment]
mm.. looking again at their models, it looks like the one I tried does not exists anymore, it was a v-neck. So I am not sure about the fitting but I suspect it will be roughly the same. We can always ask for new samples if we want I guess

**Comment by yofiesetiawan** [comment]
Just to give an idea...

![tshirt-template](https://cloud.githubusercontent.com/assets/2810823/12779490/d284bab0-ca9a-11e5-8a0f-b3d4e0c388bf.png)

**Comment by davehunt** [comment]
Thanks @yofiesetiawan, I do like the wordmark with the runners. What do others think about this design?

**Comment by davehunt** [comment]
If you're interested in a Mozilla Running Club shirt, add your details here: https://public.etherpad-mozilla.org/p/running-shirts

**Comment by davehunt** [comment]
I've had a sample of the running shirt, and it's a really lightweight and breathable fabric - perfect for running in. Depending on the temperatures you're running in, you may want to use a base layer though. Here's a photo of me wearing the men's size 6. Based on this I'm changing my order to a size 7 for a little extra room.

![img_8881](https://cloud.githubusercontent.com/assets/122800/13284903/47b98888-daef-11e5-8602-6a216911d0ec.jpg)

**Comment by LucyeoH** [comment]
@davehunt looks like you got some awesome designs here. Is this issue ready to close?

**Comment by davehunt** [comment]
@LucyeoH yeah, I think the design part is over, thanks! If anyone is interested in following along from here, let's use the [running club mailing list](https://groups.google.com/a/mozilla.com/forum/#!members/running).

**Comment by davehunt** [comment]
@seeam could you provide your orange runner shield with motion lines as a high quality image with transparent background? It would be great to have one version without the wordmark, and one version with it. Thanks!

@jenpez could you provide a high quaility version of your runners both with and without the wordmark, with a transparent background? Thanks!

**Comment by seeam** [comment]
Here it is!
[Mozilla Running Club Logo.zip](https://github.com/mozilla/Community-Design/files/146229/Mozilla.Running.Club.Logo.zip)

**Comment by davehunt** [comment]
Thanks @seeam. Could you also provide a version with the wordmark in white or light grey? I'm hoping to have the shirt color to be blue, and the dark grey doesn't provide enough contrast to make it readable.

**Comment by seeam** [comment]
Here you go.
[Mozilla-Running-Club-Logo-white.zip](https://github.com/mozilla/Community-Design/files/146722/Mozilla-Running-Club-Logo-white.zip)

**Comment by jenpez** [comment]
@davehunt <https://github.com/davehunt> Here are the logos, let me know if
you have any issues with them.

**Comment by davehunt** [comment]
Here's the designs so far. Comments and feedback welcome!

![front](https://cloud.githubusercontent.com/assets/122800/13363094/b31bb458-dcbf-11e5-8fda-84345655e5cc.png)
![side](https://cloud.githubusercontent.com/assets/122800/13363098/b6300d88-dcbf-11e5-8160-c4fb99514c41.png)
![back](https://cloud.githubusercontent.com/assets/122800/13363102/b8732bc0-dcbf-11e5-979d-e6edff325c8d.png)

**Comment by elioqoshi** [comment]
@davehunt looking good! the runners and the Mozilla logo should be white though, would be the best. :)

@seeam could you push final source files to our repo via a new folder? @ariestiyansyah can help if you need to

**Comment by seeam** [comment]
@elioqoshi done!

**Comment by jenpez** [comment]
@davehunt Here's the logo with the runners and Mozilla logo in white.
![mozillarunningclub](https://cloud.githubusercontent.com/assets/16767717/13556754/a830000c-e3af-11e5-92fc-ab89addd0f31.png)

**Comment by elioqoshi** [comment]
@jenpez do you have it in vector format or higher resolution? The resolution you provided is quite not suitable for print.

**Comment by jenpez** [comment]
@elioqoshi I tried to send the vector file as a zipped file but github wouldn't accept it. I made the png larger and saved it at 300dpi.
![mozillarunningclub](https://cloud.githubusercontent.com/assets/16767717/13583454/6dafa54c-e47f-11e5-89bc-9858689a57e1.png)

**Comment by elioqoshi** [comment]
Then upload the vector file somewhere and link here @jenpez :)
Thanks!

**Comment by jenpez** [comment]
@elioqoshi Done!
https://www.dropbox.com/s/txe35b1doraub0q/MozillaRunningClub.eps?dl=0

**Comment by davehunt** [comment]
Thanks everyone. Here's the shirt updated with the latest graphics:
![front](https://cloud.githubusercontent.com/assets/122800/13596952/a7141d48-e50d-11e5-8e96-e418ef9c2cf9.png)
![back](https://cloud.githubusercontent.com/assets/122800/13596963/b50095c6-e50d-11e5-9893-1900f462e385.png)

**Comment by elioqoshi** [comment]
Looking great! Thanks guys!
@ariestiyansyah could you push to repo please? :D
