### ISSUE TITLE
Mozilla Indonesia Community - Mascot Launch Event Design Materials

### ISSUE THREAD

**Issue by yofiesetiawan** [mozilla/Community-Design#13]
Design Materials:
1. Poster - A3
2. Backdrop - 500x220cm

Detail information please check
http://mozilla.or.id/en/events/jakarta/108-mozilla-indonesia-mascot-launch.html
https://reps.mozilla.org/e/mozilla-indonesia-community-mascot-launch/

**Comment by yofiesetiawan** [comment]
Assigning to my self, collaborating with Petshopbox Studio...

**Comment by yofiesetiawan** [comment]
Drafted the layout..

![mozilla-mascot-launch-poster](https://cloud.githubusercontent.com/assets/2810823/12391247/edb8b9a0-be18-11e5-8055-a77e0b61b2af.jpg)

**Comment by elioqoshi** [comment]
Love it! Apart the fact you used Comic Sans :P

**Comment by LucyeoH** [comment]
This is adorable! Is it done? Could this possible be.... our first closed (accomplished) community design project?!?!! :open_mouth:

**Comment by elioqoshi** [comment]
@yofiesetiawan please update with the latest preview and file sources and close if done :)

**Comment by ariestiyansyah** [comment]
@elioqoshi @LucyeoH  @yofiesetiawan  better we have folder or branch to specific design created, for example in Community-Design repo create new folder called mozilla-indonesia to store all Mozilla Indonesia asset.

**Comment by elioqoshi** [comment]
Please feel free to push, I'm not a good pusher :D

**Comment by ariestiyansyah** [comment]
Please merge this pull https://github.com/mozilla/Community-Design/pull/14

**Comment by yofiesetiawan** [comment]
Latest Preview, replaced comic sans with comic neue...
![mozilla---mascot-launch-poster](https://cloud.githubusercontent.com/assets/2810823/12405938/1856325c-be7b-11e5-981b-13d3858f1938.jpg)

**Comment by yofiesetiawan** [comment]
Design of the backdrop... 
![mozid-mascot-launch-backdrop](https://cloud.githubusercontent.com/assets/2810823/12455837/c84a7042-bfcf-11e5-908c-0da09ffe2cbb.jpg)

**Comment by yofiesetiawan** [comment]
![mozilla-mascot-launch-poster](https://cloud.githubusercontent.com/assets/2810823/12952817/7738ba48-d04a-11e5-96f4-82b0c9628c01.jpg)
Squared design for social media promotions...

**Comment by elioqoshi** [comment]
@yofiesetiawan can we get the source files of these files here?

**Comment by yofiesetiawan** [comment]
Source Files:
[mascot-launch-backdrop.eps.zip](https://github.com/mozilla/Community-Design/files/126845/mascot-launch-backdrop.eps.zip)
[mozilla mascot launch poster square.psd.zip](https://github.com/mozilla/Community-Design/files/126847/mozilla.mascot.launch.poster.square.psd.zip)
[mozilla mascot launch poster.psd.zip](https://github.com/mozilla/Community-Design/files/126846/mozilla.mascot.launch.poster.psd.zip)

**Comment by elioqoshi** [comment]
@ariestiyansyah can you push these to the repo?
