### ISSUE TITLE
Mozilla Monthly Speaker Series Branding

### ISSUE THREAD

**Issue by gitbiz** [mozilla/Community-Design#15]
**Goal:** Visual digital assets promoting Mozilla monthly speaker series

**Info:** 
* Posters
* Postcards
* Email headers
* Flyers
* Corsica digital display screens

**Style Information:** Layout should include images and be along the lines of these:
* Images - photos of our various speakers at [this link](https://www.flickr.com/photos/bisgeier/albums/72157653096551079)
* Other images e.g. bios and photos on the [AirMo channel](https://air.mozilla.org/channels/speaker-series/ )
* [Potential layout](https://neighbourhoodschemes.files.wordpress.com/2015/12/january-event-posters-1-page-001.jpg?w=500 )  (not for look & feel): the top text could be consistent name for Series, ideally we’d swap out image and text below. If image is too hard to swap out, we can pick one of our ‘15 speakers for the image 
* [Another potential layout idea](http://www.sabanciuniv.edu/HaberlerDuyurular/Documents/SR_/TEDx_Poster.jpg ) (not using for look & feel); the images could be standard and text at bottom customizable to month 
* Maybe we infuse images or words into the Firefox logo along [these lines](http://payload229.cargocollective.com/1/1/60819/6885159/jknight_tedx.logo22.jpg )
* Or have topics emerge from the Fox along [these lines](http://theinspirationroom.com/daily/print/2013/3/tedx_john_lennon.jpg)? 
* I like the prominence of this speaker in [this one](http://2.bp.blogspot.com/-bsna3NnDaYI/VTEjzchpBAI/AAAAAAAAE7Y/t5UiA1MLPow/s1600/Yemen_event_poster.jpg) -- maybe we have one photo of a speaker surrounded by other speaker photos?

**Deadline:** Final version by Thurs Feb 11 so we can use to promote our Feb 25 event
**Tag:** Design Needed, Developer Needed, Staff Support Needed]

**Comment by gitbiz** [comment]
Project Brief originally submitted to Creative  in late '15 here: https://docs.google.com/document/d/1CCdLuCfe8KJ_CR83OY-B8mDFxmJQ879WkMybaO_H5J4/edit#heading=h.z6mzzyb9khi1

**Comment by gitbiz** [comment]
also reference to other design work we've had for Internal Coms posters here: https://mozilla.netx.net/public/6hrGHMsH/Mozlando_Followup_Artwork.zip

**Comment by elioqoshi** [comment]
I can take this on by Feb 2nd, but I'd appreciate if someone else might chime in in the meanwhile

**Comment by elioqoshi** [comment]
Seems no one chimed in yet. Sorry I'm late on this but I can get this done if it's still needed.

**Comment by Mte90** [comment]
What is the developer help needed?

**Comment by elioqoshi** [comment]
Not sure to be honest. @gitbiz ?

**Comment by gitbiz** [comment]
hey guys-
Apologies for the confusion -- we thought we'd need developer help and
realize the scope was less (and timeline faster) than expected.

Elio, maybe we should close this one out?

d

On Thu, Feb 11, 2016 at 11:47 AM, Elio Qoshi <notifications@github.com>
wrote:

> Not sure to be honest. @gitbiz <https://github.com/gitbiz> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/Community-Design/issues/15#issuecomment-183033407>
> .
> Untracked with Trackbuster <https://trackbuster.com/?sig>
>



-- 
Diane (Bisgeier) Tate
415 250 1724
http://about.me/dbiz

**Comment by elioqoshi** [comment]
@gitbiz is this not needed anymore or are we too late?

**Comment by gitbiz** [comment]
correct Elio - we can close this out. thank you!

On Thu, Feb 11, 2016 at 1:00 PM, Elio Qoshi <notifications@github.com>
wrote:

> @gitbiz <https://github.com/gitbiz> is this not needed anymore or are we
> too late?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/Community-Design/issues/15#issuecomment-183058084>
> .
>



-- 
Diane (Bisgeier) Tate
415 250 1724
http://about.me/dbiz

**Comment by gitbiz** [comment]
thank you!

On Thu, Feb 11, 2016 at 1:36 PM, Elio Qoshi <notifications@github.com>
wrote:

> Closed #15 <https://github.com/mozilla/Community-Design/issues/15>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/Community-Design/issues/15#event-547787066>.
>



-- 
Diane (Bisgeier) Tate
415 250 1724
http://about.me/dbiz

**Comment by elioqoshi** [comment]
@gitbiz please feel free to file again if needed :)

**Comment by gitbiz** [comment]
thank you - I just might :-)

On Thu, Feb 11, 2016 at 2:18 PM, Elio Qoshi <notifications@github.com>
wrote:

> @gitbiz <https://github.com/gitbiz> please feel free to file again if
> needed :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/Community-Design/issues/15#issuecomment-183082218>
> .
> Untracked with Trackbuster <https://trackbuster.com/?sig>
>



-- 
Diane (Bisgeier) Tate
415 250 1724
http://about.me/dbiz
