### ISSUE TITLE
Mozilla Netherlands Logo

### ISSUE THREAD

**Issue by Timmaks** [mozilla/Community-Design#17]
Can you propose a new logo for the dutch community, http://www.mozilla-nl.org ?

Goal: replacement of the current community logo
Info: Website, twitter, facebook
Style Information: Please suggest something
Deadline: yesterday ;-)
Tag: Design Needed

**Comment by elioqoshi** [comment]
Hey @Timmaks , can you please edit your issue according to issue guidelines please?


- Goal: [What you'd like created]
- Info: [What it will be used for/where it will go]
- Style Information: [What you want it to look like, link to references, similar things etc.]
- Deadline: [When would you like this done by]
- Tag: [Design Needed, Developer Needed, Question, Staff Support Needed]

**Comment by Timmaks** [comment]
Goal: replacement of the current community logo
    Info: Website, twitter, facebook
    Style Information: Please suggest something
    Deadline: yesterday ;-)
    Tag: Design Needed

**Comment by elioqoshi** [comment]
What do you think about this Tim?

![preview](https://cloud.githubusercontent.com/assets/5436686/12448725/56e102c4-bf78-11e5-8040-4d83ddfa4a0d.jpg)

**Comment by Timmaks** [comment]
Thanks!
will post a link to the mailing list so other members can give there opinion

**Comment by elioqoshi** [comment]
Great @Timmaks !
P.S: Will you be at FOSDEM?

**Comment by Fjoerfoks** [comment]
Well proposed idea!
Some remarks:
- I would like to see the text "mozilla" as large as "Netherlands" is right now
- I would like to see the text "Netherlands" as large as "mozilla" is right now
- "Netherlands" should be all lower case, "netherlands" or all uppercase "NETHERLANDS" which ever looks best
- I like the "Rocketmill". Adding a firestarter at the bottom would make it even more powerfull.

**Comment by elioqoshi** [comment]
Hey @Fjoerfoks 

I don't think Rocketmill is a good idea. This is not a startup to depict it that way. Kind of loses the cultural touch.

Also, most Mozilla community logos have the wordmark in lowercase or first letter upper case. Check Mozilla Slovenia for example:
http://www.mozilla.si/

Generally, the first letter is always upper case, we haven't used lower case in the past years a lot, so it is advised to keep it that way.

Here is a vertical version:
![nl](https://cloud.githubusercontent.com/assets/5436686/12449808/21bcd5b6-bf80-11e5-86bb-4a5a7440bd97.jpg)

**Comment by Fjoerfoks** [comment]
Can you also create one with the Dutch word "Nederland"?

**Comment by elioqoshi** [comment]
Of course @Fjoerfoks , it's a small thing

**Comment by elioqoshi** [comment]
Here we go:

![preview](https://cloud.githubusercontent.com/assets/5436686/12465811/57fbe7f2-bfd0-11e5-999a-702b85b54c7c.jpg)

**Comment by ariestiyansyah** [comment]
@elioqoshi can you provide the vector/psd/png file? thanks

**Comment by elioqoshi** [comment]
I will, after @Timmaks and @Fjoerfoks are happy with it :)
Can we close this guys?

**Comment by Fjoerfoks** [comment]
Fine by me.

**Comment by Timmaks** [comment]
Thanks @elioqoshi , in our next community meeting i will present this as a proposal for the new logo.

**Comment by elioqoshi** [comment]
@Timmaks what decision did you take?

**Comment by Timmaks** [comment]
@elioqoshi the meeting of last week was canceled, we are now planning a new meeting before the end of February

**Comment by elioqoshi** [comment]
Please let me know, so we can wrap this up

**Comment by Timmaks** [comment]
Theo community has choosen your design. Thanks. Can you provide a format we can use for the website, Facebook etc.

**Comment by Timmaks** [comment]
@elioqoshi can you push it to https://github.com/Mozilla-Nederland/Resources/tree/master/logo?

**Comment by elioqoshi** [comment]
@Timmaks sorry for the delay! Here is it:
https://github.com/mozilla/Community-Design/tree/master/Mozilla-Netherlands

Feel free to clone/fork it

**Comment by Timmaks** [comment]
Thanks!
