### ISSUE TITLE
Mozilla Science Lab's Working Open Workshop Banner

### ISSUE THREAD

**Issue by acabunoc** [mozilla/Community-Design#2]
The Mozilla Science Lab is hosting our first Working Open Workshop in Berlin this February. 

We didn't have time to make a banner graphic for the event, so we just used a MozFest photo as a placeholder here: https://mozillascience.org/working-open-workshop-february-2016

**Goal**: Banner image for our Working Open Workshop

**Users**: Our community of researchers, developers, librarians and more.

**Where will this be used**: This will appear at the top of the [landing page](https://mozillascience.org/working-open-workshop-february-2016) and possibly in material we have at the Workshop itself.

**Example of similar work**: For MozFest we had a banner graphic explaining the open science space:
https://mozillascience.org/mozfest-2015

**Due date**: late January (or earlier!)

**Branding**: Mozilla Science Lab - http://mozillascience.org/

Landing page issue: https://github.com/mozillascience/plan/issues/38

**Mozilla Science Lab logo**: https://assets.mozilla.org/portal/assets/#category/23

**Dimensions**: no hard requirements, roughly 2000 x 1000 px

**Comment by elioqoshi** [comment]
Thank you @acabunoc ! We will be taking a look at this as soon as possible. 
I also added the link to the Mozilla Science lab in your original post:
https://assets.mozilla.org/portal/assets/#category/23

**Comment by acabunoc** [comment]
amazing, thank you!

**Comment by elioqoshi** [comment]
@acabunoc Also, what dimensions should the image be?

**Comment by acabunoc** [comment]
No hard requirements, but our banners are usually roughly 2000 x 1000 px.

Let me know if you need any other details! Thanks again :)

**Comment by elioqoshi** [comment]
@acabunoc taking on this as we speak

**Comment by acabunoc** [comment]
Thanks so much, Elio! Looking forward to seeing your work :)

**Comment by elioqoshi** [comment]
@acabunoc does this work?
![banner-01](https://cloud.githubusercontent.com/assets/5436686/12445423/72d3eb5e-bf64-11e5-94ae-a8558eaa3e76.jpg)

**Comment by acabunoc** [comment]
Hey @elioqoshi -- thanks so much, this is great. Nice and simple! I'll run it by the other Science Lab staff and see what they think :)

**Comment by acabunoc** [comment]
^ @zee-moz @auremoser @kaythaney @arlissc @stephwright

**Comment by kaythaney** [comment]
great work, @elioqoshi - thank you!

**Comment by elioqoshi** [comment]
My pleasure! :)

**Comment by auremoser** [comment]
Very nice! Thanks!

**Comment by arlissc** [comment]
this looks amazing ...

**Comment by stephwright** [comment]
Nicely done @elioqoshi !!!

**Comment by zee-moz** [comment]
hi @elioqoshi thanks for doing this! love how you've integrated our existing design element, the leaf-blob thing, into this cool patterned matrix! 
a couple comments:
 on the banner is that there's a line of those leaf/blob things on the right edge that get cut off, but it's just a tiny edge and it looks awkward. can we center the graphics so both edges of the leaf-blobs cut off, which will make it feel more like an endless matrix-y expanse of leaf-blobs, or maybe just delete that edge on the far right? 
also, can we try the leaf blobs in another color range than the grey, which feel too cold/colorless to me-- maybe a blue that matches our web banner? 
thanks for your help on this :)

**Comment by zee-moz** [comment]
pale yellow tones like the ones in the center of the logo might also work-- i can see these need to be light/pale somewhat neutral so as no to compete with the logo, but it might be nice to get some color in there!

**Comment by acabunoc** [comment]
@elioqoshi if it helps with @zee-moz's cut off edge request, we don't need a strict 2:1 ratio for the banner :) 

Thanks again!

**Comment by elioqoshi** [comment]
Thanks!
@zee-moz Thanks for the valuable feedback, you are right indeed :)
Here we go:

![blue-01](https://cloud.githubusercontent.com/assets/5436686/12464816/34994dd6-bfcb-11e5-95b9-c85a68c3dc0d.jpg)
![yellow-01](https://cloud.githubusercontent.com/assets/5436686/12464817/34a114da-bfcb-11e5-9448-9d4054a7f5c1.jpg)

**Comment by elioqoshi** [comment]
In true open source fashion, here is also the pattern design in SVG.
Feel free to (un)license it under CC0 (Public Domain)

http://elioqoshi.me/owncloud/index.php/s/gv7anbpjTCpvz8k

**Comment by acabunoc** [comment]
@zee-moz what do you think? Is this good to close?

@elioqoshi we're using this on two of our event pages now -- thank you so much!

**Comment by zee-moz** [comment]
I think this looks fantastic! Love them both! Thanks for your help! :)

**Comment by acabunoc** [comment]
Hey @elioqoshi would you happen to have the source files for the banners you made here? I'm hoping to remix this for our Global Sprint :) If not, I can work off the svg you shared!

Thanks!

**Comment by elioqoshi** [comment]
@acabunoc the SVG is in fact the source file :D

**Comment by acabunoc** [comment]
Ah, thanks @elioqoshi! For some reason I thought it was just the background :)

**Comment by elioqoshi** [comment]
@acabunoc Sorry, you were right, I just included the pattern! Here is the proper one:
http://elioqoshi.me/owncloud/index.php/s/FNdgrFFZAkXCrfP

**Comment by acabunoc** [comment]
Oh man, I thought there was some special designer magic I couldn't figure out! Thanks Elio :)
