### ISSUE TITLE
Triagebot

### ISSUE THREAD

**Issue by mhoye** [mozilla/Community-Design#20]
We're rolling out some new functionality for Triagebot shortly, and I'd like some feedback/guidance about how to make it look better, starting with a new logo!

https://triagebot.mozilla.org/

The goal of TriageBot is to make it super easy for people to help us triage incoming issues, so something roboty and helpful would be nice to have. I'd like to turf out that all-the-things bit ASAP.

**Comment by flukeout** [comment]
Here are some quick sketches of some friendly bots serving up bugs...

![image](https://cloud.githubusercontent.com/assets/25212/12599688/fdf31974-c448-11e5-8dcc-72341bf45bd3.png)

**Comment by elioqoshi** [comment]
Thanks @mhoye ! Count me in for the logo here :)
I will be able to give this some time only later next week, so everyone else: feel free to chime in in the meantime.

**Comment by mhoye** [comment]
YAAAAASSSS

These are GREAT

**Comment by seeam** [comment]
Hi, I have created a simple sand-stone design. I am not good with illustration and logo. So, I've temporary used a stock robot from here: http://pixaroma.com/little-robot-character/ 
I think @elioqoshi will come up with a better robot or logo and we can replace that with this robot. But what do you think about the interface, @mhoye?
![homepage_triagebot](https://cloud.githubusercontent.com/assets/7550283/12793106/14683bc6-cad9-11e5-82ad-a97764b6455e.jpg)

**Comment by mhoye** [comment]
Holy crap. 

That is amazing.

**Comment by mhoye** [comment]
I think we should use our own robot, for sure, but that mockup is _fantastic_.

**Comment by mmhyamin** [comment]
Should we start coding?

**Comment by elioqoshi** [comment]
Looking great @seeam 
We discussed with @mart3ll that we should refrain from using logos for separate projects when we can avoid it, as we are One Mozilla. 
Let me get his thoughts on that

**Comment by elioqoshi** [comment]
@seeam can you share PSD?

**Comment by mhoye** [comment]
I think there's an acceptable distinction between "a Mozilla logo" and this non-Mozbranded robot cartoon idea, and I'm willing to make that distinction mostly because I like the robots a lot.

**Comment by seeam** [comment]
@elioqoshi not as a logo but don't you think we can use a mascot or just an illustration of a bot serving bug? However the robot I have used is shared with a CC license so we can use it by giving credit to it's author.
I have attached the PSD.
[TriageBot_Homepage.zip](https://github.com/mozilla/Community-Design/files/126614/TriageBot_Homepage.zip)

**Comment by elioqoshi** [comment]
Feel free to join the community design call today at 5:15pm UTC to discuss this among other things :)

**Comment by LucyeoH** [comment]
@mhoye looks like you got an awesome robot here! Is this done and ready to close?

**Comment by mhoye** [comment]
This is pretty great, let me leave this open until I've implemented it though.

**Comment by elioqoshi** [comment]
@mhoye implemented and ready to close? ;)

**Comment by mmhyamin** [comment]
@mhoye where is the current repo of TriageBot?

**Comment by mhoye** [comment]
https://github.com/mhoye/Canutist/

Sorry for the delay.

**Comment by mhoye** [comment]
Thank you!
