### ISSUE TITLE
Community Servicedesk Logo

### ISSUE THREAD

**Issue by TomFarrow** [mozilla/Community-Design#25]
So, I'd love to have a logo for the community hardware team, to start building a bigger, branded presence, to enable some more growth.

We provide laptops and other IT hardware to contributors across Mozilla from older stock that Mozilla has.

Would be really excited for some help here!

**Comment by Ken-Saunders** [comment]
Is the <a href="https://wiki.mozilla.org/Community_Hardware">MozillaWiki page</a> currently the only place with information about the program? I'm wondering if you already have a theme somewhere to go by.
If not, are there any plans to create a mozilla community type site or blog?
Any specific requests for colors, logo, identity, etc?

<blockquote>We provide laptops and other IT hardware to contributors across Mozilla</blockquote>
Back in 2009, I was a recipient of Mozilla's generosity. My 13" CRT monitor died, I requested a replacement (same size and res), I was sent a beautiful 24" flat screen.
I have visual issues so it was and still is greatly appreciated. Back then it was called the <a href="https://wiki.mozilla.org/Community:CommunityProgram">Community (Giving) Program</a>.

While I try to give back to Mozilla and just help out in general whenever I can, I am especially excited about the opportunity to give creating a logo for y'all a shot. Despite the "I have visual issues" comment, I'm passionate about art and have been creating it for a long time.

<a href="http://www.accessfirefox.org//mozilla-cz/mozilla-cz-logos.html">Here</a> are some (draft) graphics that I recently made for <a href="https://github.com/mozilla/Community-Design/issues/24">mozilla.cz's request</a>.
I also make all of the graphics for <a href="http://www.accessfirefox.org/">Access Firefox</a> and my other sites, and <a href="http://kensaunders.deviantart.com/">here's</a> my deviantART</a> page.

**Comment by elioqoshi** [comment]
As discussed with @mart3ll we try to refrain from logos which separate the project's identity from Mozilla as a whole. Artwork would make more sense here.

Is this related to MozOpenhard @TomFarrow ?

**Comment by TomFarrow** [comment]
Mozwhat? ;)
I'm going to assume no, because I've never heard of that.

**Comment by elioqoshi** [comment]
http://mozopenhard.mozillafactory.org/

**Comment by TomFarrow** [comment]
no, not related at all.

**Comment by Ken-Saunders** [comment]
https://github.com/Ken-Saunders/Mozilla-Community-Hardware-Logos

**Comment by elioqoshi** [comment]
@Ken-Saunders Sorry, but your proposals are very far from the Mozilla Brand Guidelines. Please take a look at them so you get a feel of it:

https://www.mozilla.org/en-US/styleguide/

@TomFarrow I will send in a proposal next week

**Comment by jkachhadia** [comment]
![moz2](https://cloud.githubusercontent.com/assets/12187577/13310316/f44ff77e-dbaa-11e5-94b5-5086dec8e879.png)

**Comment by jkachhadia** [comment]
how's this ? @TomFarrow

**Comment by TomFarrow** [comment]
Could we make the text a solid colour?

I really like the graphics, the text is just a little unclear and doesn't
quite conform with Mozilla's standard branding.

On Thu, 25 Feb 2016 at 05:11, Jay Kachhadia <notifications@github.com>
wrote:

> how's this ? @TomFarrow <https://github.com/TomFarrow>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/Community-Design/issues/25#issuecomment-188617726>
> .
>
-- 
Tom Farrow
Community Web Services
Mozilla

**Comment by TomFarrow** [comment]
(Another thing, can we go ahead and change from "community hardware" to
"community Servicedesk"? Scope of the project has expanded but the branding
still most definitely works!)
On Thu, 25 Feb 2016 at 08:53, Tom Farrow <tom@mozilla.org.uk> wrote:

> Could we make the text a solid colour?
>
> I really like the graphics, the text is just a little unclear and doesn't
> quite conform with Mozilla's standard branding.
>
> On Thu, 25 Feb 2016 at 05:11, Jay Kachhadia <notifications@github.com>
> wrote:
>
>> how's this ? @TomFarrow <https://github.com/TomFarrow>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/mozilla/Community-Design/issues/25#issuecomment-188617726>
>> .
>>
> --
> Tom Farrow
> Community Web Services
> Mozilla
>
-- 
Tom Farrow
Community Web Services
Mozilla

**Comment by jkachhadia** [comment]
@TomFarrow made the text color solid and and now it's clear!
![moz22](https://cloud.githubusercontent.com/assets/12187577/13318390/7acf4d7e-dbe0-11e5-9005-812636e54631.png)
![moz23](https://cloud.githubusercontent.com/assets/12187577/13318389/799fa32c-dbe0-11e5-99eb-88e480f0a95e.png)

**Comment by TomFarrow** [comment]
Almost there :)

How does it look if we lower case the 's' and make the 'community
Servicedesk' a colour that isn't red
On Thu, 25 Feb 2016 at 11:25, Jay Kachhadia <notifications@github.com>
wrote:

> @TomFarrow <https://github.com/TomFarrow> made the text color solid and
> and now it's clear!
> [image: moz22]
> <https://cloud.githubusercontent.com/assets/12187577/13318390/7acf4d7e-dbe0-11e5-9005-812636e54631.png>
> [image: moz23]
> <https://cloud.githubusercontent.com/assets/12187577/13318389/799fa32c-dbe0-11e5-99eb-88e480f0a95e.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/Community-Design/issues/25#issuecomment-188739675>
> .
>
-- 
Tom Farrow
Community Web Services
Mozilla

**Comment by jkachhadia** [comment]
there you go @TomFarrow  :)
![moz223](https://cloud.githubusercontent.com/assets/12187577/13319251/8f8f218e-dbe6-11e5-9592-5df7e30b0dce.png)

**Comment by elioqoshi** [comment]
@jkachhadia Thanks for the submissions! Unfortunately they are out of our branding guidelines. Please check our style guide and other official Mozilla logos to get a better understanding of the branding:
https://www.mozilla.org/en-US/styleguide/

@TomFarrow I can give this a try next week if you like.

**Comment by elioqoshi** [comment]
![1](https://cloud.githubusercontent.com/assets/5436686/13554467/c3731dba-e3a8-11e5-9011-1603f258c664.jpg)

My proposal here.

**Comment by TomFarrow** [comment]
Thanks Elio.

That's awesome.

Can you send me the typical web+print exports? :)

**Comment by elioqoshi** [comment]
@TomFarrow here we go:
http://elioqoshi.me/owncloud/index.php/s/GFDGBvZkjKJrh9f

@ariestiyansyah can you push this into our repo? :)
