### ISSUE TITLE
Working party report - automated mainstream work

### ISSUE THREAD

**Issue by chrisglasier** [mozilla/Community-Design#26]
## Goal: 
The same kind of initial research banks required prior to considering the introduction of eBanking. In this case it is an initiative in pursuit of the goals of Mozilla’s Strategic Narrative for 2016 and Beyond.

## Info:
To be used for:

1. Accountability to donors particularly those from the general public. 
2. If positive, basis to proceed to detailed feasibility studies.

## Style Information:
My only concern is that it includes appraisal and agreement/disagreement of the following propositions:

1. Automated mainstream work is a major development in the use of the Web/Internet pertinent to Mozilla's mission.
2. Key design characteristics of personal eBanking web pages and websites that use analysis of multiple web sources are relevant.
3. Working practice suitable for automation is based on digital objects rather than digital versions of paperwork.
4. The ability to assemble objects that define different working practices is a form of web literacy.
5. Assembly needs to be automatically coded and laid out to universal standards to handle complexity and diversity of objects and their physical, financial and time-related aspects. 
6. HTML5, CSS, JavaScript and JSON data interchange format are considered relevant technology.
7. Interoperable assemblies of digital objects open new opportunities for accessing multiple web sources relevant to different objectives in different industries to establish a new way of working.

## Tag:
This needs to be administered by a staff member.
[Staff Support Needed]

## Deadline: 
See above

**Comment by chrisglasier** [comment]
Separating and expanding propositions for related comments/disagreement/agreement

1. Automated mainstream work is a major development in the use of the Web/Internet pertinent to Mozilla's mission.

Definitions

Automated - change to mechanised as more suitable; introduce machines or automatic devices into (a process or place).
(https://www.google.com.hk/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=define%20mechanised)

mainstream : The ideas, attitudes, or activities that are shared by most people and regarded as normal or conventional.
(http://www.oxforddictionaries.com/definition/english/mainstream)

work: physical or mental effort or activity directed toward the production or accomplishment of something.
(http://www.thefreedictionary.com/work ) 

Major development -

Just as the introduction of personal computing was to use of computers so mechanising mainstream work is to use of the Web.

Mission

Mozilla's mission is "to ensure the Internet is a global public resource open and accessible to all". Knowledge of computer coding, although beneficial, cannot practically be a prerequisite. The remaining propositions need expanding to explain how they support the underlying vision, role and work pillars.

**Comment by chrisglasier** [comment]
_Separating and expanding propositions for related comments/disagreement/agreement_

2. Key design characteristics of personal eBanking web pages and websites that use analysis of multiple web sources are relevant.

A personal eBanking page is actually a machine interface very similar to the physical screen display on an ATM. Many people use both to work on their own information made available from a single automated source. Available options are determined by banks with the interface custom made accordingly and subject to their approval.

Many people can use similar machine interfaces on websites that analyse many web sources, for example, to find best deals for hotels, flights and so forth. Sites are independently designed with options determined from designers' own arrangements with the industry sector to be analysed. Many individuals can select different options to work on many pertinent analyses from many sources.

Elements that characterise existing mechanisation - machine interfaces, analysable information pertinent to specific industries and devices needed for analyses and display of results - are relevant to mechanised mainstream work. However, in order to handle complexity and diversity, a new universal machine interface design and set of interaction protocols is required to ensure interoperability and unrestricted expansion.

**Comment by chrisglasier** [comment]
_Separating and expanding propositions for related comments/disagreement/agreement_

3 Working practice suitable for automation is based on digital objects rather than digital versions of paperwork.

Here the term digital object means a named dataset that can acquire different information from different sources to support different objectives. For example, a joinery manufacturer uses a table object to identify its components, compute cost, manage production and so on. Purchase of the table includes its digital object with selected parts of the dataset. If the customer is a restaurateur, other information might be added to help manage layout, bookings, waiting services and QAQC. Each object is independent but can be combined into one or more associations using link arrays. If required devices can use objects to generate digital versions of paperwork.

**Comment by elioqoshi** [comment]
Let me reconfirm, is volunteer contribution needed here? In any case, thanks for posting the issue!

**Comment by chrisglasier** [comment]
What I am asking for is for an assessment whether Mozilla should accept or decline my contribution. If it is accepted then it will really benefit from participation from both volunteers and staff. Please also see my note to Lucy [here](https://discourse.mozilla-community.org/t/time-limit-for-github-issues/6904/2).

**Comment by elioqoshi** [comment]
@chrisglasier I understand, but how is that related to community design?

**Comment by chrisglasier** [comment]
I saw it as a prerequisite to the start of community design. But I am new here and would be happy to take  your advice. Please also see my latest note to Lucy [here](https://discourse.mozilla-community.org/t/time-limit-for-github-issues/6904/4).

**Comment by elioqoshi** [comment]
Sorry, I am unable to comprehend the request and fail to see how it is related with Community Design (groundwork at least). In this meaning, this discussion should be held on Discourse, not on GitHub where design requests are sent in
