### ISSUE TITLE
Update the style of the Firefox Style Guide to match Firefox’s In-Content Preferences.

### ISSUE THREAD

**Issue by bwinton** [mozilla/Community-Design#31]
## Goal: 
Update the style of the [Firefox Style Guide](http://firefoxux.github.io/StyleGuide/) to match Firefox’s In-Content Preferences.

## Info: 
The Firefox UX team is creating a style guide, focused on Firefox, partially to help Add-on authors create extensions that look “Firefox-y”.  We have a first pass at the style guide live at the link above, but it would be nice if the left-hand section matched our In-Content preferences, instead of using a totally new style.  We would also like to add some documentation on the style of the In-Content preferences, which is currently lacking, as well as providing a CSS file to make it easy for add-on authors to make pages that follow that style.

## Style Information: 
An example of the In-Content Preferences style can be seen at `about:preferences`.
The source files for that style can be found [here](https://dxr.mozilla.org/mozilla-central/source/browser/themes/osx/preferences/in-content/preferences.css) and [here](https://dxr.mozilla.org/mozilla-central/source/browser/themes/shared/incontentprefs/preferences.inc.css).  (We don't want to use those directly, but instead want to copy the styles we need from them into a simpler stylesheet.)
The stylesheet we want to create should go in [this directory](https://github.com/FirefoxUX/StyleGuide/tree/gh-pages/src/styles).

## Deadline: 
Soon-ish.  :wink:  (We'ld like to release the Style Guide in the next week or two, and it would be nice for this project to be a part of that, but we're happy to release it with the current styles if we don't get this completed in time.)

## Mentor: @bwinton

**Comment by elioqoshi** [comment]
Thank you @bwinton ! Does this need staff guidance?
@Mte90 might be interested?

**Comment by Mte90** [comment]
So what is the help as a developer?
to transform the style of that page with the internal design of firefox?

**Comment by elioqoshi** [comment]
As far as I could understand, yes!

**Comment by bwinton** [comment]
@elioqoshi: I'm staff, so any staff guidance should be readily available.  :wink:
@Mte90: Yep, to make the style of that page (particularly the part on the left) look more like the style of about:preferences!

**Comment by Mte90** [comment]
I have started working on that https://github.com/FirefoxUX/StyleGuide/pull/31

**Comment by bwinton** [comment]
Awesome, thank you!  :grinning:

**Comment by LucyeoH** [comment]
@bwinton I added you as the "Mentor" and turned this into a "Mentored Issue" since it seems like it will use regular check-ins and support from staff to make sure it's on course. Is that cool?

**Comment by bwinton** [comment]
Sure, although I think it's already mostly done!  :smiley:

**Comment by Mte90** [comment]
![screenshot3](https://cloud.githubusercontent.com/assets/403283/13015477/9e165b6e-d1b9-11e5-850b-4a8bc3bc280b.png)
Finished!

**Comment by elioqoshi** [comment]
@Mte90 Can you make the icons a tiny little bit bigger? It should be perfect then!

**Comment by Mte90** [comment]
Uhm I have tried but with css is not possible, the only way is change the size of every svg.

**Comment by elioqoshi** [comment]
Let's do it then. Can you do it yourself or do you need help?

**Comment by Mte90** [comment]
I can do it, actually the size is 16x16 but before to change all the dimensions I await @bwinton because I chosen the icons and I am not sure about these.

**Comment by bwinton** [comment]
And I think we're good to close this.  (I don't want to change the sizes of the source SVGs, so if we want to make them bigger, we'll need to figure out a different way, but in either case, I think what we have now is good enough to close this bug.  :wink:)
