### ISSUE TITLE
Logo Design

### ISSUE THREAD

**Issue by ecwebservices** [mozilla/Community-Design#33]
I'm looking for a design for a logo. I already have one (that's used as my profile picture zoomed in), but I'm looking to get a better, higher resolution logo.

## My logo:
![ecws-badge-square](https://cloud.githubusercontent.com/assets/14031707/13028921/4bbf26fe-d243-11e5-8a37-c98cd0fdb3d9.png)

If someone can supply this I'll be much appreciated.

**Comment by MedMack** [comment]
Hey, does this have any relation to Mozilla (products, communities, other,..) ? if so, what improvements you are seeking exactly ?
