### ISSUE TITLE
Create a logo for the Transvision project

### ISSUE THREAD

**Issue by pascalchevrel** [mozilla/Community-Design#34]
## Goal: 
We would like a logo for the Transvision project
https://transvision.mozfr.org/

Transvision is the translation memory web application created by the French Mozilla community and now maintained by both staff from Mozilla l10n-drivers team and volunteers (mostly French). If you don't know what a translation memory is, it is a tool that indexes all the translations for all languages in Mozilla products + mozilla.org every day and allows to search for these translations. This is used by translators to ensure translation consistency over time but it is also used by translation tools (Mozilla Pontoon, OmegaT or the European Commission tools) to retrieve translation suggestions that help localizers translate faster.

We opened an issue on our github repo 2 years ago to ask our community to create a logo https://github.com/mozfr/transvision/issues/223 but our community is mostly comprised of developers and translators, not graphic designers.

## Info: 
It will be used to identify the Transvision project and will be displayed at the top of our pages. We would also like that logo to be identifiable as a favicon and probably not too colorful to allow printing it at low cost on T-shirts and stickers for our community.

## Style Information: 
The logo should fit well in the style of the site, here is a search showing the colors we use:
https://transvision-beta.mozfr.org/?recherche=test&repo=aurora&sourcelocale=en-US&locale=fr&search_type=strings

Although we may change of design over time, it is very likely that it will keep using light colors.
Here is how the site looked like over time:

2010: https://blog.babelzilla.org/2010/02/07/transvision-is-good-for-me/
2012: https://blog.babelzilla.org/2012/10/18/transvision-comparison-feature-makes-l10n-qa-easier/
Today: https://transvision.mozfr.org/

Currently the favicon displayed is the one for the French community but something distinct would allow communicating about Transvision as a multi-locale tool and not as something related to the French language (our logo http://bonjourmozilla.fr/public/.logo_mozfr_m.jpg is a red panda and its tail has the colors of the Francophone countries flag http://www.francophonie-avenir.com/Archives/Francophonie-drapeau.jpg).

## Deadline: 
Whenever you can :)

## Tag: 
[Design Needed, Developer Needed, Question, Staff Support Needed]

**Comment by jkachhadia** [comment]
![moz](https://cloud.githubusercontent.com/assets/12187577/13309942/7e80e9de-dba7-11e5-8fc6-f78b161b386e.png)

**Comment by jkachhadia** [comment]
@pascalchevrel check the above logo for transvision!

**Comment by flodolo** [comment]
Thanks for the proposal. There are a few issues the way I see it: 
* Transvision is not just about Firefox, it's a about several Mozilla projects (Firefox, Thunderbird, SeaMonkey, mozilla.org, Firefox for iOS, Fennec). If it has graphic references, it should be to Mozilla.
* I don't think it can scale down gracefully to small sizes with this amount of details.

**Comment by jkachhadia** [comment]
![moz11](https://cloud.githubusercontent.com/assets/12187577/13311858/fc30e77a-dbb7-11e5-8183-af20faf74c45.png)
![moz12](https://cloud.githubusercontent.com/assets/12187577/13311859/fdae18ac-dbb7-11e5-9051-b3f3decb75ca.png)

**Comment by jkachhadia** [comment]
@flodolo this solves the problem and is relating as well :)

**Comment by pascalchevrel** [comment]
I like the simplicity of the logo, but it is a bit high in vertiality I think. I am thinking of how we can integrate it on the website or as a favicon while keeping its readability.
@TheoChevalier  what do you think?

**Comment by TheoChevalier** [comment]
I really like the shadow-less version :)

Yeah, I think it's too high as well, but I like the idea behind it.
The "T" should be easy to turn into a favicon, maybe with a wider white strip to render as 1px-wide on a favicon.

**Comment by jkachhadia** [comment]
@pascalchevrel   @TheoChevalier 
I was thinking that we could use only T or the graphic above T as the favicon and this one as the the entire logo for transvision? Or do we need some changes?

**Comment by flodolo** [comment]
A couple of thoughts:
* I'd really like the idea of a favicon that could be more recognizable that the single letter. The first part of the icon is the "international standard icon" for localization, so we might generate confusion there.
* I would also try an alternative palette of colors.

**Comment by elioqoshi** [comment]
@pascalchevrel @flodolo Here is my proposal.

I added the eye icon and arrows to indicate "Trans - Vision" symbolically.
I personally prefer the bottom one. What do you think?

![draft-01](https://cloud.githubusercontent.com/assets/5436686/13554256/826cc92e-e3a3-11e5-9b93-e79811bb5626.jpg)

**Comment by elioqoshi** [comment]
@pascalchevrel @flodolo Looking forward to your feedback :)

**Comment by pascalchevrel** [comment]
I really like the last iterations :+1: 
I don't know if we can use the mozilla wordmark because although this is a software largely developed by Mozilla employees, it is not an "official" mozilla project on a mozilla.org domain, it's a community project on which Mozilla puts resources.

The third logo is more sophisticated but I don't know how it would fit as a favicon, maybe we should take one of the elements only for the favicon.

**Comment by flodolo** [comment]
Same here. I like the colors and the icon in the third version, we should probably try to resize it down to 16px to check what's understandable if we use it as favicon.

**Comment by elioqoshi** [comment]
Using the Mozilla wordmark should be no problem here. I have created dozens of internal logos until now and this goes under the category where it should be okay :)

Looks good to me as a favicon. If in doubt, we can choose just the 2 cards in plain colors for a favicon. Preview here:

![transvision](https://cloud.githubusercontent.com/assets/5436686/13688818/97483ad4-e724-11e5-8f07-0f5029e81cd9.jpg)

What do you think?

**Comment by flodolo** [comment]
The empty cards look a bit anonymous, while the first version (even if 32px) looks still recognizable. Personally I really like it.

**Comment by elioqoshi** [comment]
@flodolo I'd suggest using the empty cards for 16x16 if needed. for 32x32 we can use the original one like usual. :)

**Comment by elioqoshi** [comment]
btw, the empty cards is just to show the scale down, it would be used only for the smallest resolution.

**Comment by pascalchevrel** [comment]
I am convinced :+1:  Thanks Elio, that looks very nice, Can you upload an archive with all the files to this issue and I'll work today on integrating the logo to our site :)

**Comment by elioqoshi** [comment]
@pascalchevrel My pleasure! Will push soon to the repo with all needed files :)

**Comment by elioqoshi** [comment]
@pascalchevrel here we go!
https://github.com/mozilla/Community-Design/tree/master/Transvision

**Comment by pascalchevrel** [comment]
Here is the logo integrated on our dev site https://transvision-beta.mozfr.org/ (we also added you to our credits page).
