### ISSUE TITLE
Need Characters Created for Campus Campaign Website

### ISSUE THREAD

**Issue by LucyeoH** [mozilla/Community-Design#36]
## Goal: 
We need three characters (cartoons? people? foxes?) created who can represent the three tracks of the campus campaign: 
* education & awareness
* policy & advocacy
* technology & innovation

They will go in the three circles here, but will (hopefully) appear in assets throughout the campaign: 
![02-home](https://cloud.githubusercontent.com/assets/2810823/13370818/b3372364-dd46-11e5-9b0f-738a59b5571f.jpg)

## Style Information: 
Ask @yofiesetiawan for more details!

## Deadline: 
ASAP!! March 1st or 2nd preferably!

**Comment by yofiesetiawan** [comment]
This issue relate to https://github.com/mozilla/Community-Design/issues/35
I was proposing new design for bottom, adapting @seeam design... 

![a08c9c44-dfa8-11e5-8b70-100ea96c3b85](https://cloud.githubusercontent.com/assets/2810823/13450217/9d73ae68-e065-11e5-8318-0207138d847b.jpg)

**Comment by elioqoshi** [comment]
Is the campaign website layout finished with only the characters remaining?
I will reach out to some friends of mine to help out here. @Raphseck is this something for you?

**Comment by yofiesetiawan** [comment]
I would love to get rid the 'hero image' and highlight the characters, later..

**Comment by Raphseck** [comment]
great layout
Loved

**Comment by elioqoshi** [comment]
@Raphseck can you come up with 3 characters like you did for your other projects?

**Comment by Raphseck** [comment]
yes i can! : )
lets do this

**Comment by elioqoshi** [comment]
Awesome! Let us know if you need help

**Comment by Raphseck** [comment]
Hey guys!
Here some sketches of BASIC characters without big characteristics!
What do you thing about this path?
(and sorry about my english) : /

![sketches](https://cloud.githubusercontent.com/assets/14264676/13579272/59d37de0-e47b-11e5-8b64-39d8a9bc97b2.png)

**Comment by LucyeoH** [comment]
Thank you so much! These are adorable and I think there are a number of places we can use them!! Could you send me the files for the foxes?  

For the front page we found some old graphics that  we adapted to represent the three impact areas! 

Thanks again!!

![screen shot 2016-03-03 at 12 13 32 pm](https://cloud.githubusercontent.com/assets/8070833/13580286/8603e082-e46f-11e5-979c-495a693350d8.png)

**Comment by Raphseck** [comment]
@LucyeoH great graphics! :)
loved!

Ok!! 
what foxes?
My badges or those sketches?

**Comment by elioqoshi** [comment]
@LucyeoH They look great! However, them having the same pose and expression make them look a bit repetetive. It would be great if they could have some slight differences.

@Raphseck We need a characterpack by you, these are amazing!

**Comment by MichaelKohler** [comment]
Really like the one with the header image. I'm not sure if we need a clean
design here.

**Comment by elioqoshi** [comment]
I like the 1st alternative too, it has more human touch. Further, the faces of Mozillians might be too obscured in the image, maybe the very first try was better? But maybe I'm biased as I am in that photo :P

**Comment by yofiesetiawan** [comment]
Little adjustment...
![04-home](https://cloud.githubusercontent.com/assets/2810823/13680566/ad7537d8-e72b-11e5-96b6-8178a19ff4fd.jpg)

**Comment by elioqoshi** [comment]
My face is back in, approved!

lol jk, but this looks better imo :)

**Comment by elioqoshi** [comment]
The menu items should be on the right, near Tabzilla, or not?

**Comment by MichaelKohler** [comment]
It should be to have consistency.
