### ISSUE TITLE
FOSSASIA Name Card Design

### ISSUE THREAD

**Issue by ariestiyansyah** [mozilla/Community-Design#38]
## Goal: 
[What you'd like created]

Ask Me Anything about Mozilla Design

## Info: 
[What it will be used for/where it will go]

Please help us design name card used for FOSSASIA 2016 event with text "I am Mozillians! Ask Me Anything about Mozilla"

## Style Information: 
[What you want it to look like, link to references, similar things etc.]

Name Card

## Deadline: 
[When would you like this done by]

Soon before 17 March 2016

## Tag: 
[Design Needed, Developer Needed, Question, Staff Support Needed]

**Comment by ariestiyansyah** [comment]
@elioqoshi can you help us?

**Comment by elioqoshi** [comment]
Yep, leave this to me :)

**Comment by elioqoshi** [comment]
I need more details: dimensions and the fossasia vector logo

**Comment by francjp** [comment]
Hi @elioqoshi,

I don't think that we need the fossasia logo for this, since the plan is to use it on other events. The dimensions would be a business card.

The plan is to give to people at events, as a way to contact, or icebreaker.

Thanks

**Comment by elioqoshi** [comment]
Aha, I thought that would be a lanyard badge. Why don't we go with our original Mozillians Business card design?

**Comment by francjp** [comment]
Could it be an option... where do we have that?
But in any case, I want to add the "Ask me anything about Mozilla..." in the Reps business card, that will be lost... I can make something, but I need to know the font.

**Comment by francjp** [comment]
Closing this one, since there wasn't any feedback, or reply, and we are running out of time with this. We will sort it out without a design.

Cheers,

**Comment by elioqoshi** [comment]
argh sorry, forgot to followup here, maybe a bit more buffer next time
