### ISSUE TITLE
Mozilla Hyderabad Logo design

### ISSUE THREAD

**Issue by viswanathamsantosh** [mozilla/Community-Design#44]
## Goal: 
Mozilla hyderabad has been one of the most active community with active volunteers in many diversified projects and having a logo will help us for more for more branding and reachout at various Non-mozilla community events around Hyderabad. 

## Info: 
Designing posters, Club launch programs, To put the logo up at other Technical meetups and conferenences around hyderabad.

## Style Information: 
Charminar is an heritage monument. want a logo with it.

## Deadline:  
by the end of April 1st week.

More information about mozilla hyderabad
https://www.facebook.com/MozillaHyderabad/?ref=hl
http://mozillahyderabad.org/

## Tag: 
[Design Needed, Developer Needed, Question, Staff Support Needed]

**Comment by elioqoshi** [comment]
Thanks Santosh! Taking this on :)

**Comment by viswanathamsantosh** [comment]
Thank you elio! :)

**Comment by parag9d** [comment]
I would love to pitch in some ideas too :)

**Comment by parag9d** [comment]
Tried 2 versions of the logo. Combining Charminar (Popular monument of Hyderabad) and the fox for Mozilla. The second version has the world map in the background (like the Mozilla logo) with the focus on India.

What do you guys say?

![mozilla hyderabad logo-01](https://cloud.githubusercontent.com/assets/6411097/14077767/bf4e6f4e-f50c-11e5-942b-4fad14ca2630.png)
![mozilla hyderabad logo-02](https://cloud.githubusercontent.com/assets/6411097/14077768/bf4ff94a-f50c-11e5-93ec-b69803fe4555.png)

**Comment by parag9d** [comment]
Another version with some modifications...
![mozilla hyderabad logo v2-02](https://cloud.githubusercontent.com/assets/6411097/14078041/ea306a5c-f50f-11e5-8d47-a56597573aaa.png)

**Comment by parag9d** [comment]
Tried one more version with the India map. In my opinion this is the most balanced one...what do you say?
![mozilla hyderabad logo-02](https://cloud.githubusercontent.com/assets/6411097/14078605/bf55f6d0-f514-11e5-8449-8c61a53868a7.png)

**Comment by parag9d** [comment]
@viswanathamsantosh Let me know what you think about this. Also see this for better understanding:
http://giphy.com/gifs/fox-mozilla-hyderabad-xThuWgTKatVpNE0gQ8

**Comment by viswanathamsantosh** [comment]
@parag9d Perfect! Thank you so much. I think we can finalize the one with india map. :)

**Comment by parag9d** [comment]
Cool, here is the high-resolution version of the logo:
https://www.dropbox.com/s/6fhtwjewo6k6kjy/Mozilla%20Hyderabad.png?dl=0

**Comment by parag9d** [comment]
@viswanathamsantosh You got the high-resolution image, right?

**Comment by viswanathamsantosh** [comment]
Yes! Got the high resolution image as well as the gif. thanks :D

**Comment by parag9d** [comment]
@viswanathamsantosh cool, there were some minor modifications after the last update. So, be sure you have the latest one from that Dropbox link :)

**Comment by elioqoshi** [comment]
@parag9d awesome work! There is some inconsistency with the wordmark which needs fixed. Also please always upload the source files here, so all of our work is collected here. 

Can you link to it here and I can give it a look?

**Comment by elioqoshi** [comment]
Also, there is no need for the map of India in the background, it's too much to include I'd say

**Comment by Ryuno-Ki** [comment]
@elioqoshi Just out of curiosity:

> There is some inconsistency with the wordmark which needs fixed.

Can you elaborate on that? I want to understand what you noticed.

**Comment by elioqoshi** [comment]
@Ryuno-Ki I'd be happy to, but I'd need the source files. @parag9d please the source files so we can go on.

**Comment by parag9d** [comment]
The source file was already added in the community design github repo.

**Comment by elioqoshi** [comment]
Okay @parag9d but please do a headsup when updating :)
