### ISSUE TITLE
FSA Promotional Video

### ISSUE THREAD

**Issue by fayetandog** [mozilla/Community-Design#49]
## Goal: 
Create a 2-min or less promotional video about the FSA program, what we do and why should students join.

## Info: 
It will be used online and offline, especially for offline events so it will be easier to explain the FSA program and can be played on booths. Taking the opportunity as there is also a campus campaign going on.

## Style Information: 
https://youtu.be/I6MbOtWyaKE
This was done by FSAs in the PH.
We are also brainstorming the messaging and resources to use in this doc: https://docs.google.com/document/d/1McRPeWLEQEZLYv2D_GzRL7P4w3hPeoZipn9B1HS7D0Q/edit?usp=sharing

## Deadline: 
May 2016

## Tag: 
Design Needed

## Note:
@jhnchrstnmrqz @jasminpalanca @analynarcilla and the other FSAs who created the video above committed to work on this. Adding this to Community Design so other people can also pitch-in their ideas and perhaps make the team for this bigger!

**Comment by LucyeoH** [comment]
@fayetandog can we hold up on this project for now. I think it would be great if we could integrate Campus Campaign into this messaging.

**Comment by LucyeoH** [comment]
Closing temporarily! :)
