### ISSUE TITLE
Standard rollup banner asset

### ISSUE THREAD

**Issue by Mte90** [mozilla/Community-Design#5]
On http://assets.mozilla.org/ there are rollup banner for specific capaign but no standard banner to customize for the various community.
As an example a banner with Firefox logo that we can add the local community logos.

**Comment by yofiesetiawan** [comment]
Basically we can adjust the design from mozilla assets to have some space for local community logo. If someone need that, they can specify specific the size they need. So we can execute... Not sure, but maybe different places have different standard sizes for banner... 

I share an example here.. 
![banner-sample](https://cloud.githubusercontent.com/assets/2810823/12253012/0ea5f6b4-b90f-11e5-9795-83319caf41aa.jpg)
This is only preview in 72dpi, do not print with this.

If you want to print you can use this file (76.2cm x 152.4cm, 150dpi) https://dl.dropboxusercontent.com/u/4450713/mozilla/banner/banner-firefox-simple.psd

**Comment by Mte90** [comment]
Something like that is not bad, maybe adding a text area ready with the Fira font for custom text and the mozilla logo can be perfect for every use.

**Comment by elioqoshi** [comment]
I think this is easy enough to do on a case by cases basis. So people can request it directly here.

**Comment by Mte90** [comment]
Maybe have a portfolio will be not bad to choose the base.

**Comment by elioqoshi** [comment]
We can do that as we go with concrete requests.

**Comment by elioqoshi** [comment]
@yofiesetiawan can you take this over? I was thinking of general Firefox banners with different background colors.

2 dimensions preferably:

- 200x80cm
- 76.2cm x 152.4cm

Kind of like this:

![firefox](https://cloud.githubusercontent.com/assets/5436686/12443555/e8a1c3e4-bf58-11e5-80db-11f8a873a1e7.jpg)

**Comment by yofiesetiawan** [comment]
I finally abble to get rid of the annoying shadow.. I hope that's okay? No shadow in flat design? Haha..

![firefox-banner-landscape](https://cloud.githubusercontent.com/assets/2810823/12456521/d22d2f3e-bfd2-11e5-90ba-fc6c8263a1e5.jpg)
![firefox-banner-portrait](https://cloud.githubusercontent.com/assets/2810823/12456522/d2812ba2-bfd2-11e5-8144-56811a7175f2.jpg)

Download Source Files:
https://dl.dropboxusercontent.com/u/4450713/mozilla/GitHub/firefox-banner-200x80cm.ai
https://dl.dropboxusercontent.com/u/4450713/mozilla/GitHub/firefox-banner-762x152mm.ai

**Comment by elioqoshi** [comment]
@yofiesetiawan thanks! In fact I meant 80x200cm vertically as some banners use that dimension. Also please put in the shadow under the Firefox logo again as it's part of the logo.

Further please export in EPS CMYK as AI is no open format.

**Comment by yofiesetiawan** [comment]
Here are the EPS files:
https://dl.dropboxusercontent.com/u/4450713/mozilla/GitHub/firefox-banner-80x200cm.eps
https://dl.dropboxusercontent.com/u/4450713/mozilla/GitHub/firefox-banner-200x80cm.eps
https://dl.dropboxusercontent.com/u/4450713/mozilla/GitHub/firefox-banner-762x152mm.eps

**Comment by elioqoshi** [comment]
Updated JPG previews too please @yofiesetiawan :)

**Comment by yofiesetiawan** [comment]
Preview 

80x200cm
![80x200cm](https://cloud.githubusercontent.com/assets/2810823/12499288/d9d76416-c0db-11e5-9d5a-5d64e292892d.jpg)

200x80cm
![200x80cm](https://cloud.githubusercontent.com/assets/2810823/12499289/db9d303c-c0db-11e5-98b8-52f74b71620a.jpg)

7620x1524mm
![7620x1524mm](https://cloud.githubusercontent.com/assets/2810823/12499290/dbed1e8a-c0db-11e5-9d6b-1e39be2879f9.jpg)

**Comment by Mte90** [comment]
maybe add that on assets.mozilla.org will be helpful for others

**Comment by yofiesetiawan** [comment]
@Mte90 not sure how to do that? Someone here can help to add this to assets? @elioqoshi

**Comment by elioqoshi** [comment]
We need staff approval to add these to assets. We can discuss that in the next meeting. Thanks @yofiesetiawan !
@ariestiyansyah can you push the 3 design eps and jpg into the repo?

**Comment by ariestiyansyah** [comment]
Done push image to master branch
https://github.com/mozilla/Community-Design/commit/12363d653ea8faa432f1204e795cedd56790577f
