### ISSUE TITLE
Icon for Mozilla Eir Program

### ISSUE THREAD

**Issue by kaichih** [mozilla/Community-Design#50]
## Goal: 
We would like to create an icon for Mozilla Eir project: 
https://wiki.mozilla.org/Eir

## Info: 
It would be used for the github in Eir project: 
https://github.com/mozeir

## Style Information: 
No preference, as long as the icon can reflect what we are doing in this project. 

## Deadline: 
As soon as possible. 

## Tag: 
[Design Needed]

**Comment by parag9d** [comment]
Do you want a logo or icon for this project? Although branding is not my forte, I would be more than happy to help out in this :)

Is there anything I can do to help in the UI or UX front?

**Comment by kaichih** [comment]
Hello, sorry to reply it late. 

Actually, we need both a logo and an icon for this project. A logo we can use on the program Wiki or other places. An icon that we can also use in Github. 

Are you talking about the UI or UX front in this project? If that's what you talking about, YES!!! We REALLY need help!! :)

**Comment by parag9d** [comment]
Hi @kaichih! Yes, I would like to help in the UI and UX for this project. Also, I will also try to help with the logo and the icon :)

**Comment by anistuhin** [comment]
@elioqoshi and @yofiesetiawan we need someone here :)

**Comment by elioqoshi** [comment]
helping out here as soon as I can

**Comment by elioqoshi** [comment]
![eir](https://cloud.githubusercontent.com/assets/5436686/14490377/c9ed8e40-0172-11e6-868a-b7e95deb85c6.jpg)

What do you think of this?

**Comment by kaichih** [comment]
Looks good for me! Thanks!!!

**Comment by parag9d** [comment]
@kaichih I want to contribute to the UI and UX design of the project. Can you please connect me with the right person for that. Thank you.

**Comment by kaichih** [comment]
Awesome! @parag9d, please feel free to join our Google Group: https://groups.google.com/forum/#!forum/open-iomet. Also, it would be great if you could input your name, skill sets and other information in the following spreadsheet: 
https://docs.google.com/spreadsheets/d/1kWzx8lcZcOLkVB2Ie79zzVNHWEIt9mUL7jgWOkeD3i4/edit#gid=0
