### ISSUE TITLE
Take Back the Web/Campus Campaign Google Doc Template Needed

### ISSUE THREAD

**Issue by charissalaisy** [mozilla/Community-Design#53]
## Goal: 
As part of the campus campaign we're giving students resources/activities to run at their university. We'd like these to be hackable and easy to use, which is best on Google docs.

So, we need a template for Google docs that we can drop text into easily, with our logo ( #52 ) and some design features to make our resources look good!

## Info: 
This will turn into a Word doc and PDF, but we need to be able to drop text into it easily.

## Style Information: 
Here is an example of the resources we're creating: https://docs.google.com/document/d/1XXyozZ5b1PYlEZJ171srBDuBu3E7Li5I6J6evr0NRn8/edit?ts=56f2e92c#heading=h.oibm22z5g0ag 

So there are different buckets like Goals, Challenge, Details, etc. The buckets are similar in the other resources, but the buckets text should also be editable.

Here is a description of Google doc templates: http://www.makeuseof.com/tag/24-google-docs-templates-will-make-life-easier/

And here is our website with our colors and design: https://takebacktheweb.mozilla.community/ 

## Deadline: 
Friday, 4/8

## Tag: 
Design Needed

**Comment by elioqoshi** [comment]
Sorry for failing to deliver on this, feel free to ping if this is still needed.
