### ISSUE TITLE
Review Curriculum Slide Design

### ISSUE THREAD

**Issue by emmairwin** [mozilla/Community-Design#55]
## Goal: 
Consult on slide creation/design for Mozilla Curriculum Workshop

## Info: 
https://github.com/mozilla/community-teaching-training/issues/1

## Deadline: 
april 8th

## Tag: 
Question

**Comment by anistuhin** [comment]
What kind of developer support do you expect, @emmairwin ?? I might be available :)

**Comment by emmairwin** [comment]
sorry, no developer support - consultation and maybe design support.

**Comment by elioqoshi** [comment]
I see deadline is over. Do you still need this @emmairwin ?

**Comment by Junaed33** [comment]
I'm available to share my ideas and knowledge with you. Please let me know if you still needs help.
