### ISSUE TITLE
The web needs a replacement for Bootstrap/Foundation

### ISSUE THREAD

**Issue by autonome** [mozilla/Community-Design#58]
## Goal: 
I'd like a replacement for Bootstrap that makes my content look good with zero work, but without all the downsides of requiring terrible markup, redundant classes and huge downloads.

Developers are going to continue to use Bootstrap and similar frameworks for as long as there's no better alternative to make their content look "good enough".

So instead of fighting them, let's *help* them... by creating an alternative which is lightweight, uses modern layout features like flexbox/grid, and looks *fabulous*.

## Info: 
The project deliverable will be a CSS file that can be used by developers everywhere.

## Style Information: 
It should style the defaults of web content in a similar "unspecifically good enough" way that projects like Bootstrap and Foundation do.

http://getbootstrap.com/
http://foundation.zurb.com/

It should have a look and feel that, out of the box (eg no added CSS classes), would make non-designers think "hey, that looks good".

## Deadline: 
ASAP.

## Tag: 
Design Needed

**Comment by Ryuno-Ki** [comment]
I would like to see Demos included as well (Copy&Pastable snippets).

Bootstrap has the advantage of some feedback from the accessibility community whereas Foundation is more fancy (IMHO) :-)

@autonome What about JavaScript dependencies? Bootstrap relies heavily on jQuery …

**Comment by autonome** [comment]
@Ryuno-Ki Great idea for demos/snippets. We cannot fight copy+paste coding... instead we must embrace it by improving the quality of what is copied and pasted :)

Re JS dependencies. Ideally there would be none. However, some functionality might require it. I'd love to see a gracefully-degrading framework. For example, if you only include the main css file, you get a basic set of features. If you include the JS, you can more features. I think the whole idea though is to try and see how much we can get from as little as possible.

**Comment by anistuhin** [comment]
Great thing to play with, but do you have anything in mind for this: out of the box (eg no added CSS classes), I mean without JS and all. Btw what do you mean by "Design needed" in Tag, Graphics for different components or developers as well to work on the CSS??

**Comment by Ryuno-Ki** [comment]
> For example, if you only include the main css file, you get a basic set of features. If you include the JS, you can more features.

Are you sure, that this is [graceful degradation](https://en.wikipedia.org/wiki/Fault_tolerance)? It sounds more like [progressive enhancement](https://en.wikipedia.org/wiki/Progressive_enhancement) to me (which I favour more).

Also choosing a JavaScript framework could be tricky as there are [so many of them](http://www.planningforaliens.com/blog/2016/04/11/why-js-development-is-crazy/). Maybe we can find an agnostic way or provide several.

IMHO Community-Design is not the right repo for it. It's not a design issue. There are [plenty articles listing several frameworks in the wild](http://www.cssauthor.com/css-frameworks/), so maybe a guide tool is rather helpful: You answer some questions (like: browser support, number of columns, fix-width vs. responsive and so on) and will be presented three or four fitting frameworks.

**Comment by autonome** [comment]
I think a guide is a very useful, but separate idea.

I do not think including a JS framework solves the problem I'm talking about, and is headed off in the wrong direction.

What I'm looking for should be entirely design. If someone here is interested in doing the visual design and UX, perhaps that's a start. We could continue by building out the CSS using modern patterns and web technology approaches.

**Comment by autonome** [comment]
@anistuhin Hi! See the previous comment. There are a few components to the project, probably. The primary component is the visual design, and secondarily is implementation in CSS.

**Comment by Ryuno-Ki** [comment]
[![Standards](https://imgs.xkcd.com/comics/standards.png)](https://xkcd.com/927/)

**Comment by davidascher** [comment]
FYI, there's related work we're doing in MoFo to harmonize all of our sites.  The CSS templates live at https://github.com/mozilla/mozmaker, but follows a complicated and ambitious branding & IA audit.

**Comment by davidascher** [comment]
Oh, rereading comment #0, I think I misunderstood the purpose.  And I think I disagree w/ it.  I would agree w/ a proposal to submit a PR to bootstrap that leverages flexbox however ;-).

**Comment by autonome** [comment]
@Ryuno-Ki Luckily, design isn't like standards!

@davidascher Unfortunately Bootstrap has more downsides than just flexboxlessness. And it's the fastpath to "good enough" web UI for a whole lot of developers.

I'm interested in creating a lighter-weight and lower-overhead fastpath for "good enough" default visual style.

**Comment by davidascher** [comment]
@autonome: how would you rate/describe any of the ones on e.g. https://github.com/neiesc/ListOfMinimalistFrameworks#framework-for-css ?

This seems like a place where lots of people are trying to do "lightweight", but it seems that "users" are picking larger frameworks in practice (I don't have actual data, this is just heuristics), which makes me think that the 'user need' isn't yet clearly articulated (making it hard to design for).

**Comment by elioqoshi** [comment]
@Mte90 might be interested in this

**Comment by Mte90** [comment]
I love bootstrap for me is not bloated or redundant, the markup now is very simple and the same as amount for all the complete frameworks to support all the platform/devices/etc and have a big amount of plugin and extensions.
Maybe the first step is analyze what you don't like to find something that have not problem and next define something.
I think that today the more simple and powerful that have is perfect for that ticket is http://semantic-ui.com/

**Comment by Ryuno-Ki** [comment]
A framework which [implements meaningful CSS](http://alistapart.com/article/meaningful-css-style-like-you-mean-it) could be interesting.

**Comment by elioqoshi** [comment]
Do we have a goal for this? If yes, feel free to reopen it.

**Comment by Mte90** [comment]
Actual there is https://github.com/mozilla/mozmaker that is official and the demo on https://mozilla.github.io/mozmaker/demo/

**Comment by autonome** [comment]
@davidascher thanks for that list!

I want to work with @belen-albeza to develop a framework to evaluate CSS frameworks. Developers are going to use them no matter what, so we should help them make educated choices of framework.

@elioqoshi I think this is worth doing, but I think maybe this isn't the right place to do it, so am reluctant to re-open the issue. So far, the conversation is from non-designers saying that I don't want what I'm saying I want. They just don't understand my vision. (/me flips hair back glamorously)

**Comment by ecwebservices** [comment]
If your looking for a css framework ECKit is a good try. It's my try at one, but I haven't done much on it.

**Comment by elioqoshi** [comment]
@autonome this is a bit chinese for me, so feel free to ping me if i need to do any action :D
