### ISSUE TITLE
Logo design for Mozilla's Best of Web

### ISSUE THREAD

**Issue by remcokaptein** [mozilla/Community-Design#59]
## Goal: 
I'm looking for a logo for a program at Mozilla we call "Best of Web". The logo will be used for promotion purposes when we start kicking off the survey for "Best of Web". The current efforts are focused on Germany.

## Info: 
Still determining. It will likely be used in "Snippets" which are located below the search box on the homepage and looks like [this](https://drive.google.com/file/d/0B-13vvWwiWJ5WDNPYzVreG52OEk/view?usp=sharing). I'd like to use the same logo on Twitter and Facebook. If we make it suitable for Twitter and Facebook we can reduce size to make it suitable for Snippets as well.

## Style Information: 
I'm thinking something like [this](http://thumb10.shutterstock.com/display_pic_with_logo/708184/110073767/stock-photo-miniature-globe-with-golden-crown-isolated-on-white-background-110073767.jpg)

Should be PNG format. 

Since we target Germany first I'd like to see if we can incorporate the flag of Germany like [this](https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Flag_of_Germany_-_dimensions.svg/2000px-Flag_of_Germany_-_dimensions.svg.png)

And maybe a Mozilla twist to it...

## Deadline: 
I'd like to present it Monday or Tuesday next week, 18 or 19 April. 

## Tag: 
Design Needed

**Comment by elioqoshi** [comment]
@remcokaptein what do you think of this? It's quite cheesy, but the request itself is cheesy too :)

No german flag please, that would look bad.
![icon-01](https://cloud.githubusercontent.com/assets/5436686/14489749/37788c66-016f-11e6-8ad7-87ef6b8cc1b8.png)

.

**Comment by remcokaptein** [comment]
Thanks. 

If you think it's cheesy feel free to be creative. We are aiming for best of web services which make using Firefox more relevant for each market we're addressing.

**Comment by Raphseck** [comment]
Hey guys, how are you?
Elio asked for the following sketch of an fox
what do you think?

![fox_c](https://cloud.githubusercontent.com/assets/14264676/14588339/81f5ccaa-049d-11e6-8a15-e6b350192b95.jpg)

**Comment by remcokaptein** [comment]
I like it!

2016-04-17 18:09 GMT+02:00 Raphael Chilingue Eckhardt <
notifications@github.com>:

**Comment by kellymj** [comment]
Hey @Raphseck, that's pretty cute! I work on content for snippet and Firefox + You, and I'd like to include this in our next newsletter and on the snippet to promote the survey. May I suggest making the line weight of the crown match the outline on the fox? 

After that would you be willing to share the native vector file with me so we can resize it to meet the different graphic specs required by each channel?

**Comment by Raphseck** [comment]
hey @kellymj i would love this!
Sorry about the delay, i don't know what happened but for some reason i didn't receive the email with your answer.
Here the fox. : )

![fox_c](https://cloud.githubusercontent.com/assets/14264676/14887877/1b277804-0d2e-11e6-99ae-f26809155f59.jpg)


(sorry about my english)

**Comment by Raphseck** [comment]
and here the link for AI file! : )

https://www.dropbox.com/s/apa3kl42u3zzdd4/fox_crown.ai?dl=0

**Comment by kellymj** [comment]
Awesome! Thank you so much.

On Thu, Apr 28, 2016 at 7:03 AM, Raphael Chilingue Eckhardt <
notifications@github.com> wrote:

> and here the link for AI file! : )
>
> https://www.dropbox.com/s/apa3kl42u3zzdd4/fox_crown.ai?dl=0
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/Community-Design/issues/59#issuecomment-215433459>
>



-- 

*M.J. Kelly* | Sr. Digital Content Strategist, Lifecycle Marketing |
mjkelly@mozilla.com | IRC: mjkelly
