### ISSUE TITLE
Firefox Club Milan Logo

### ISSUE THREAD

**Issue by Mte90** [mozilla/Community-Design#6]
The first italian Firefox Club need a logo.

Site WIP: http://firefoxmilano.it/
FB: https://www.facebook.com/firefoxmilano

One of the proposal that they have received form members was the Milan skyline (ex: http://www.giaxtower.com/img/skyline.gif) in background and firefox logo over it.

Firefox Club Founders for other info: @nicokant94 @aroblu94

**Comment by nicokant94** [comment]
Another proposal was based on our University logo: bit.ly/1N2Tq0w

Thanks for your help!

**Comment by nicokant94** [comment]
I found the proposal of a guy from the club, we loved the idea he had about mixing the firefox logo and the skyline. The only problem was that the colors were too opaque.. I hope you'll consider starting from this idea ;) ![logo_full_light](https://cloud.githubusercontent.com/assets/6927678/12237129/7925c0ba-b87d-11e5-82bc-083f5b068403.png)

For further reference look for @Dasher7 on Telegram.
Thank you guys!

**Comment by LucyeoH** [comment]
@Mte90 did this work for you? Is this issue good to be closed?

**Comment by Mte90** [comment]
I've opened the ticket for @nicokant94, we need a logo for that club and that are the draft of the members but we need something cool.

**Comment by LucyeoH** [comment]
@Mte90 Cool! I've added you as a collaborator for this repo so you can add labels indicating if you need design, development, whatever! Thanks for all your posts so far!!

**Comment by LucyeoH** [comment]
@Mte90 I would re

**Comment by elioqoshi** [comment]
Assigning this to myself, but probably won't get to it before February

**Comment by MedMack** [comment]
I'm sketching a couple of ideas for this logo. @nicokant94 can you please share the source file of the first proposal logo ? This will be a big help, thanks.

**Comment by nicokant94** [comment]
I'm asking @Dasher7 to provide me the sources, I'll publish here as soon as I can.
Thank you very much for your help!

**Comment by nicokant94** [comment]
Here they are!  
![skyline](https://cloud.githubusercontent.com/assets/6927678/12619580/f1502baa-c518-11e5-849f-929ccdd1766c.jpg)
![firefox_logo-only_rgb](https://cloud.githubusercontent.com/assets/6927678/12619617/149e4ae2-c519-11e5-9a2c-ac9167be74dc.png)

**Comment by MedMack** [comment]
Hey again, thanks @nicokant94 for the first stock photo. Here is my proposal(s) for the Firefox Club Milan with small changes.
![firefoxclub_milan](https://cloud.githubusercontent.com/assets/2369504/12690728/ee284cd6-c6e5-11e5-9702-6019608d38e2.png)

**Comment by MedMack** [comment]
An other proposal where I tried the integration of the colors of the Italian flag.
![firefoxclub_milan_5](https://cloud.githubusercontent.com/assets/2369504/12690995/457165b6-c6e8-11e5-9a81-22a96753b21d.png)

**Comment by aroblu94** [comment]
Hi @MedMack, thank you very much for your work, they are beautiful!!! I have to speak with @nicokant94 and the others club members but.. could you please try using MILANO instead of MILAN please? Just curious :)
Anyway for me it's much better with MILAN (or MILANO) in capital case (3 and 5 of your sketches).

Thank you!!

**Comment by MedMack** [comment]
Hey, sorry for the late. Here is the two final logos.
![firefoxclub_milan_final](https://cloud.githubusercontent.com/assets/2369504/12702522/03ef7ebc-c82c-11e5-9e22-eb7a373fb308.png)

**Comment by aroblu94** [comment]
@MedMack don't know if it's me but I can't see them

**Comment by MedMack** [comment]
Sorry it was a problem while uploading. ![firefoxclub_milan_final](https://cloud.githubusercontent.com/assets/2369504/12721890/5111af7c-c902-11e5-9726-9c764645b6f2.png)

**Comment by MedMack** [comment]
Sorry there was a problem with the file, here is it. ![fxclub_milan_finalpreview](https://cloud.githubusercontent.com/assets/2369504/12722021/04f09ab2-c903-11e5-8630-15bd256a4d42.png)

**Comment by aroblu94** [comment]
Simply beautiful. For me those are the best, we'll wait for @nicokant94 and @Mte90 that are coming back from FOSDEM :) thank you very much

**Comment by Mte90** [comment]
they are not beautiful, but really really beautiful!
is possible to get the logo with without the shadow in the flag colors?

**Comment by MedMack** [comment]
Here is the logo with all the source files. For some reason I can't attach the .zip file here so here is the link for dropbox : https://www.dropbox.com/s/g21b4y15dd151an/Milano%20Firefox%20Club%20Logo.zip?dl=0

**Comment by MedMack** [comment]
Can someone check if this issue can be close ? Logo with source files included in the last comment. cc @Mte90 @nicokant94 - thanks.

**Comment by elioqoshi** [comment]
Thank you @MedMack!

**Comment by ariestiyansyah** [comment]
Source of Firefox Milan Logo: https://github.com/mozilla/Community-Design/commit/aa53ff82c14c1b866791fbf3f7a1de5bfca18088

**Comment by elioqoshi** [comment]
@Mte90 can you check this please?
https://github.com/mozilla/Community-Design/issues/46
