### ISSUE TITLE
Platform Operations identity art

### ISSUE THREAD

**Issue by armenzg** [mozilla/Community-Design#62]
## Goal:
We would like to have a logo for Mozilla's Platform Operations division.
Platform ops takes care of most services and tooling that enables engineers from the main Firefox products to have an effective development process plus provide the release pipeline.
Platform ops is composed of various teams:
https://wiki.mozilla.org/Platform_Operations
and here's the mission of one of the teams that can (to some extent) be applied to the whole org:
https://wiki.mozilla.org/EngineeringProductivity#Our_Mission

## Info:
We would like to use this logo to create gear, for our various websites and presentations.

## Style Information:
Here are the logos from some of the teams:
https://people.mozilla.org/~catlee/releng-banner.svg
https://tools.taskcluster.net/lib/assets/taskcluster.svg
https://wiki.mozilla.org/images/1/13/Ateam.png

There's a sense of empowering others behind this org.

## Deadline:
2nd week of May.

## Tag:
[Design Needed, Staff Support Needed]

**Comment by armenzg** [comment]
Hi @parag9d thanks for being willing to help! I've also opened this up to the rest of the community if they're willing to make proposals:
http://armenzg.blogspot.ca/2016/05/open-platform-operations-logo-design.html

Let's see who else will apply for it.

Good luck!
Armen

**Comment by eliperelman** [comment]
I had some ideas around this space so I thought I would contribute a little.

My ideas circle around "Platform Operations" being the core building blocks of Mozilla, the foundation on which things are built. So my theme revolves around these blocks.

---

##### Isometric and colorful blocks, using Fira Sans as the typeface for consistent branding.

![1](https://cldup.com/6LRHODmmmV-2000x2000.png)

---

##### The orientation of the blocks can be changed to suit whatever preference there is:

![2](https://cldup.com/pGJ6uKpnlZ-3000x3000.png)

---

##### You can also change the arrangement of the blocks for different purposes, while still retaining the same feel across different projects or purposes:

![3](https://cldup.com/a2_vdZ6DS2-2000x2000.png)

---

##### Or better yet, you could also change the color scheme to produce team-specific branding, e.g. a TaskCluster-specific branding:

![4](https://cldup.com/-u-jXPPTUL.png)

---

The possibilities are many. Just an idea. 😃

**Comment by armenzg** [comment]
@parag9d hi Parag, are you going to have time to submit some ideas before the deadline?

@eliperelman thanks for the multiple possiblities!
I like the idea of the "building blocks", what do you think of trying other objects than the cubes for experimenting? Maybe gears? Any other objects that can convey the idea of building units? or core units?
Could you also try a colour that draws from the Mozilla colour theme?

Thank you!

**Comment by parag9d** [comment]
Hi @armenzg, I am currently having a lot of work at Samsung R&D India, so couldn't give time to this. I will try to ideate something by tomorrow.

Meanwhile, I like the idea proposed by @eliperelman, I guess this draws some inspiration from Uber's redesign concept where bit were the building blocks of it and combining them new identities could be created.

I guess we can use the combination of different shapes to make one meaningful identity to depict different people with different roles coming together and solving a problem.

**Comment by armenzg** [comment]
Looking forward to it :)

**Comment by eliperelman** [comment]
@armenzg I unfortunately don't have time to play with other logo icons, but I was able to shift around the color scheme to match the [Mozilla color swatches](https://www.mozilla.org/en-US/styleguide/identity/mozilla/color/):

![4](https://cldup.com/0SYwVkdKzd-2000x2000.png)

**Comment by armenzg** [comment]
:+1: 
No worries, I understand!

**Comment by djmitche** [comment]
I really like the blocks, actually - they have the right level of visual complexity.  And I like the inverted-V orientation.  And the mozillian color scheme.  Basically I really like the most recent proposal :)

I'm not especially keen on rebranding taskcluster to match :)

**Comment by klibby** [comment]
Pretty much everything @djmitche said, except that the font used for "Operations" throws me off a little bit.

**Comment by eliperelman** [comment]
@klibby it's the same font, just not bold.

**Comment by eliperelman** [comment]
Maybe if the word "Operations" was also bold, but not black, that may help.

**Comment by eliperelman** [comment]
Bolded "Operations", with _Mozilla Red_ and _Mozilla Charcoal_:

![5](https://cldup.com/QOlR8GNTWk-2000x2000.png)

---

![6](https://cldup.com/OMp3iSdkit.thumb.jpg)

**Comment by parag9d** [comment]
I had been brainstorming on some ideas for Platform Operations based on what it does and how it works. I have used some basic mind mapping technique. I have a few ideas based on the outcomes.

I particularly like the seed > watering > fencing idea. It doesn't focus on code but shows the work process very well. What do you think? :)

![img_20160511_081323 2](https://cloud.githubusercontent.com/assets/6411097/15168981/314cdf40-1754-11e6-851a-94c7430ac524.jpg)

**Comment by catlee** [comment]
I like the blocks. To be honest, I'm not a fan of the red/black/gray colour scheme though.

**Comment by armenzg** [comment]
@parag9d I like the way you think about it. I'm mainly interested on seeing alternative options and even one without the name of the team on the logo (or small or to be used on the back of a t-shirt rather than inside the logo).

If I was to organize a meeting either tomorrow at 10am Pacific or Friday for people to brainstorm would that work for you? No more than 15-30minutes.

**Comment by lmandel** [comment]
Like @djmitche, I like the blocks as well. Other thoughts on that are using blocks for all the letters (don't think this is going to work out) or using blocks for the first P, and OP. (i.e. merge the letters with the blocks.)

@catlee Can you provide any more detail about why you don't like the colour scheme? Any suggestions for what you'd like to see with the colours?

**Comment by djmitche** [comment]
Three colors, three blocks seems sort of arbitrary.  Some other combination might look better -- two charcoal and a red? etc.

@parag9d I like the seed proposal too.  In a way, "platform" is the ground upon which engineering builds.  I don't have any idea how to make that analogy visually, though..

**Comment by lundjordan** [comment]
++ to both the blocks and seed ideas

with regards to the blocks idea:

If I were to strip down what 'platform operations' means to literally those two words, stacked or connected blocks, at least for me, highlight the 'platform' support really well. To emphasis the 'operations' side of things, I think it be cool to integrate a sort of 'puzzle' or 'gears' element that highlights how we connect and extend the blocks.

To explain my thinking, here is a logo which is real and owned by someone else but shows the puzzle pieces extending outwards from some of the blocks

![logo](https://cloud.githubusercontent.com/assets/1648433/15230333/f8a260ce-1849-11e6-8566-68aaca14585d.png)

**Comment by eliperelman** [comment]
It's funny, I was just thinking about inter-connected blocks, but what came to mind was inner stackable, almost like Russian nesting dolls. Anyway, just messing around with that on the same blocks:

![7](https://cldup.com/TQ2sy5yg-P-2000x2000.png)

**Comment by whimboo** [comment]
Platform operations as a whole consists of several individual teams which are working hand in hand together. Which means we all are building a single large block out of smaller ones. Personally I like some soft optical illusions, so maybe something like the following combined with the text and colors as uploaded by @eliperelman 3 days ago, might look kinda interesting:

![stock-vector-classic-optical-illusion-impossible-geometrical-figure-36814225](https://cloud.githubusercontent.com/assets/129603/15241755/72ab5742-18f2-11e6-9864-0f867aefdeed.jpg)

**Comment by Ryuno-Ki** [comment]
Concerning the puzzle suggestions: Aren'ty they to feature rich to work out as a logo?

From [what I've read](https://www.smashingmagazine.com/2016/04/logo-design-responsive-websites/#a-simple-fact) logos should strive to be simple. Otherwise you cannot scale them (think drop flags down to tea cups).

**Comment by catcarbonell** [comment]
Hi. I saw you wanted gears.

![platformops](https://cloud.githubusercontent.com/assets/6016111/15265030/3f00c4ca-1930-11e6-8af1-8662dc97bfa4.png)

**Comment by elioqoshi** [comment]
@armenzg Sorry for the late reply, but why do we need a logo for a such specific team within Mozilla?
@mart3ll input is appreciated here regarding his

**Comment by armenzg** [comment]
It's a myriad of teams working together to empower development and we want to bring more self-identity and visibility towards the rest of the organization.

In any case I forgot to mention that we started a survey to pick the logo we want to use and we have one now. Thanks for your interest though!

Thank you to each one involved in this thread. I need to check with my manager if we want to keep the winner unrevealed until London (to make it a surprise to the team) or if I can already reveal it.

I will hope to remember to mention it here!

**Comment by armenzg** [comment]
The org members voted and the winner is https://camo.githubusercontent.com/63b498032bde18a9a59b901f856f5a42e69af012/68747470733a2f2f636c6475702e636f6d2f514f6c5238474e54576b2d3230303078323030302e706e67

Thank you all for your participation!

**Comment by elioqoshi** [comment]
Great! Please push the files to our repo so they are easily accessible :)

**Comment by armenzg** [comment]
Hi Elio,
We have them in here:
https://github.com/eliperelman/platform-logos

Do you want to grab them from there? or put a reference to it?

On 24 May 2016 at 09:56, Elio Qoshi <notifications@github.com> wrote:

> Great! Please push the files to our repo so they are easily accessible :)
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/Community-Design/issues/62#issuecomment-221277852>
>



-- 
Zambrano Gasparnian, Armen
Engineering productivy engineer - #ateam
http://armenzg.blogspot.ca
