### ISSUE TITLE
Sticker Design for openSNP

### ISSUE THREAD

**Issue by gedankenstuecke** [mozilla/Community-Design#63]
## Goal: 
I'm looking for a sticker design for hexagonal stickers for [openSNP](https://github.com/openSNP/snpr), a [Mozilla Science Project](https://www.mozillascience.org/) working on openly sharing genetics data. We already have a general logo, [see here](https://www.dropbox.com/s/gvhcuoy893w2yyr/logo.svg?dl=0), but this isn't really suitable for stickers. Stickers we'd love to have for the upcoming sprint and conferences to hand out to people. It would be great if the design could be oriented along the line of the existing logo.

## Info: 
The design will mainly be used on the stickers.

## Style Information: 
Ideally we'd love to have hexagonal stickers as the many ones you can find at [hexbin](http://hexb.in/) for inspiration. The design should fit the [StickerSpec](https://github.com/terinjokes/StickerConstructorSpec), being a hexagon of 1.76" x 2". 

## Deadline: 
mid of May

## Tag: 
[Design Needed]

**Comment by acabunoc** [comment]
Yes, this project is part of @MozillaScience collaborate: https://mozillascience.org/projects/gedankenstuecke-snpr

**Comment by elioqoshi** [comment]
@gedankenstuecke quite late on this but here we go. I took the liberty to recreate the logo, hope you don't mind. This should fit more now. What do you think?

![1](https://cloud.githubusercontent.com/assets/5436686/15456594/8c715764-2075-11e6-9375-ce90bf3c08fd.jpg)

**Comment by gedankenstuecke** [comment]
@elioqoshi Thanks so much, those are really nice. 🎈 🎉 😍  
The general logo re-design is awesome and I like the right sticker variant a lot! 

Two minor things: 
1. Could you modify the top-right logo variant so that the space between open & SNP is a bit smaller (The "official" name of the project is openSNP)? 
2. The text/dots on the right sticker design seems to be a bit off-center to the right to me? 

It would be awesome if you could add those changes! 😃

**Comment by elioqoshi** [comment]
@gedankenstuecke will do tomorrow and you will have the final files! :)

**Comment by gedankenstuecke** [comment]
@elioqoshi Awesome, thanks so much!

**Comment by elioqoshi** [comment]
@gedankenstuecke here we go!
https://github.com/mozilla/Community-Design/tree/master/openSNP/RGB

![horizontal](https://cloud.githubusercontent.com/assets/5436686/15506039/38358290-21c6-11e6-8c38-5c16bfc7df45.png)
![sticker](https://cloud.githubusercontent.com/assets/5436686/15506041/3838c608-21c6-11e6-8449-63f043344132.png)
![vertical](https://cloud.githubusercontent.com/assets/5436686/15506040/38369c20-21c6-11e6-9433-0cae356f6d0c.png)

**Comment by elioqoshi** [comment]
Please note that these are in RGB. If you need to print them, you should convert them into CMYK

**Comment by gedankenstuecke** [comment]
@elioqoshi awesome, thanks so much. Will convert to CMYK and print those stickers. And please: eMail me your address to bgreshake@gmail.com so I can send over some of the resulting stickers! :-)

**Comment by elioqoshi** [comment]
@gedankenstuecke Thank you! No worries, we might meet at the London All Hands I guess anyway? :)

**Comment by gedankenstuecke** [comment]
@elioqoshi unfortunately we won't, but Mozfest might work out for me! :-)

**Comment by elioqoshi** [comment]
Perfect, I will grab a sticker at the next occasion then, just keep up the great work :)
