### ISSUE TITLE
Logo design for Mozilla Security Bug Bounty Program and its challenge coin

### ISSUE THREAD

**Issue by albill** [mozilla/Community-Design#68]
## Goal: 
Logo for Mozilla Security Bug Bounty Program

## Info: 
May be used on web site and business cards eventually
First use is on a "challenge coin" that will be handed out to people that report security bug bounties. See [this](http://www.coinsforanything.com/samples) for examples of what a "challenge coin" is. 

## Style Information: 
Would like to reference earlier Mozilla designs of Dino head or red star or similar. 

Facebook did a nice design, which you can see on a [sticker](https://www.flickr.com/photos/albill/25940341241/in/dateposted/) and a [t-shirt](https://www.flickr.com/photos/albill/25405048503/in/photostream/) though I think Mozilla dino is closer to what we want than skull-bugs. 

## Deadline: 
June 18, 2016 (one month)

## Tag: 
[Design Needed]

**Comment by albill** [comment]
One idea is a dino head silhouette on a shield, sort of similar to things in [this issue](https://github.com/mozilla/Community-Design/issues/46)

[sf club](https://cloud.githubusercontent.com/assets/5436686/13809832/f62592b2-eb6c-11e5-81d6-f40f8f846f04.jpg)

[firefox club diu](https://cloud.githubusercontent.com/assets/7550283/13856288/b22ac9c8-ec9e-11e5-98f6-7786db18462a.png)

**Comment by Ryuno-Ki** [comment]
Reminds me on the logo of [snyk](https://snyk.io/):

![Snyk logo](https://snyk.io/style/asset/logo/snyk-dog.svg)

**Comment by elioqoshi** [comment]
@albill why do we need a logo for this? We already have a Mozilla Security artwork/symbol. Wouldn't that fit? 
![securing mozilla_lightbackground](https://cloud.githubusercontent.com/assets/5436686/15456421/c6c6c74c-206f-11e6-8648-6009afebf15a.png)

**Comment by elioqoshi** [comment]
@mart3ll might know more also

**Comment by albill** [comment]
No, that's a generic Mozilla security logo (which doesn't even apply to my org) and this is specifically for the Mozilla bug bounty program started back in 2004. If that logo was acceptable, I would not have opened this issue. I'm making something (a coin) to give to people who find bounties in our program as a gift instead of a t-shirt and I want it to have an identifiable logo for the program on it.

(As an aside, I hate that Mozilla Security logo anyway as it isn't very meaningful or convey "security" except in words.)

**Comment by elioqoshi** [comment]
@albill well, it doesn't help saying how much you hate something, so that's the wrong approach :)
Also please adjust your tone, a logo being acceptable is "subjective"

I personally don't think a logo per se is needed for such a specific sub project. This would be more of an artwork. Not sure why you requested a logo, which would irritate our brand identity for such a specific case.

**Comment by albill** [comment]
I don't need you tone policing me. You don't know me and if you don't understand, you could ask better questions to clarify. I have no idea who you are.

It was suggested internally that this might be a good place to get help. Given your attitude, clearly not. 

Feel free to close the issue. I'll go outside Mozilla and pay someone to work on this for a fee so we can get what we actually want, not debate why we want it. Thanks and no need for you to reply.

**Comment by elioqoshi** [comment]
It is very debatable why you want it, and I suppose you haven't talked to the Creative Team before filing this request, which is kind of why I commented here. Feel free to pay for it, but that doesn't change the process to request permission to use a brand in that way like you wish to do it.

Not going into your other points, as they were plainly rude.
