### ISSUE TITLE
Mozilla's Open Sauce Artwork

### ISSUE THREAD

**Issue by cassiemc** [mozilla/Community-Design#7]
While at a Mozilla work week in Orlando in December, @xmatthewx and I overhead @vazquez misread a handwritten note on a planning calendar wall – someone had written 'open source' but it looked like 'open sauce.' Happy accident?

If we had some kind of graphic, emblem or illustration, this could make a nice swag bag addition for future events (e.g. [Mozfest](https://2015.mozillafestival.org)). It could even be a Sriracha bottle label, or a tshirt, sticker etc. 

The final format and style are really up to you! It can be black and white or color. We just ask that the final artwork be vectorized, so that we can scale it to different mediums.

**Comment by elioqoshi** [comment]
@cassiemc Am I doing this right? :D
![open sauce](https://cloud.githubusercontent.com/assets/5436686/12340074/fa77dd54-bb18-11e5-9d6d-fa6521ee1a24.jpg)
![sriracha](https://cloud.githubusercontent.com/assets/5436686/12340075/fa9351ba-bb18-11e5-97d7-af5b37a1776a.jpg)

**Comment by cassiemc** [comment]
@elioqoshi This is great!! Would love to see some of the text adapted around the graphic, so we might have to do some copywriting as well. Would be good to see how the final emblem could look in –
- [ ] bottle label form
- [ ] on a t-shirt
- [ ] on a sticker

**Comment by elioqoshi** [comment]
Srizilla Open Sauce? hehe

**Comment by mozfreddyb** [comment]
If you write "Mozilla's open source" it could be read as "Mozilla is open source" and "open source from Mozilla" 
:stuck_out_tongue_winking_eye:

**Comment by natalieworth** [comment]
+1 to Mozracha Some cool inspiration too: https://www.flickr.com/photos/infomatique/6945895316/sizes/l/in/photostream/

**Comment by xmatthewx** [comment]
that's a great reference @natalieworth !!

**Comment by LucyeoH** [comment]
Awesome work all! @cassiemc let us know if there's more here!
