### ISSUE TITLE
Community Design Jalandhar

### ISSUE THREAD

**Issue by karanverma** [mozilla/Community-Design#71]
![jalandhar mozilla](https://cloud.githubusercontent.com/assets/8354175/15480468/5c9f568e-2143-11e6-9bbd-899625590e05.jpg)
## Goal: 
[Jalandhar Mozilla Club(DAVIET) community]

## Info: 
[Community Wall]

## Tag: 
[Developed by Karan Verma]

**Comment by elioqoshi** [comment]
@karanverma Can you please explain what this is about?

**Comment by karanverma** [comment]
Mozilla Club of Jalandhar (DAVIET) .
