### ISSUE TITLE
Mozfest Volunteer Role - Sketch Design for Emma's Blog Post

### ISSUE THREAD

**Issue by emmairwin** [mozilla/Community-Design#73]
## Goal: 
 I would love to have my rough sketches for Mozfest volunteer role 'want ads' turned into images I can use for a blog post due before EOD May 31 (**tomorrow**)

I know this deadline is tight, but asking anyway!

## Info: 
It will be used in my blog post coming up before June 1  (when call for proposals goes out) and will inform the building of the actual want-ad design.

Attributes

**Title**: Mozfest Space Volunteer
**Subtitle** "Space Name"  
**Top Left:** Photo:  Generic shape of person
**Bottom left**: Name of role:  ie" Help Desk: with scribbles indicating writing (no actual text)
**Top right**:  Skills list  & Timeline 
**Bottom right:** Apply button.

(but open to better layout !)  This is super drafty to share a story doesn't have to be perfect.

## Style Information: 
Leveraging Mozfest styles available and logo
https://2015.mozillafestival.org/
https://2015.mozillafestival.org/expect

## Deadline: 
By EOD UTC May 31  

## Tag: 
Design Needed

**Comment by emmairwin** [comment]
![photo on 5-30-16 at 10 19 am 2](https://cloud.githubusercontent.com/assets/60618/15655395/a031588a-2651-11e6-8a91-ed005e5e783f.jpg)
![photo on 5-30-16 at 10 24 am](https://cloud.githubusercontent.com/assets/60618/15655394/a02f96a8-2651-11e6-9e25-70ef82468ce2.jpg)

If someone does have the time - having both of these turned into images would help me tell the story a little clearer than just one.  Thanks to anyone who may have time!

**Comment by elioqoshi** [comment]
@emmairwin here we go :)

https://github.com/mozilla/Community-Design/tree/master/MozFest2016/CfP-Images

![mozfest cfp images-01](https://cloud.githubusercontent.com/assets/5436686/15657939/50fcda86-26b6-11e6-8c0a-72c83bfb4e0b.jpg)
![mozfest cfp images-02](https://cloud.githubusercontent.com/assets/5436686/15657940/50ffb81e-26b6-11e6-997d-b64fbccd4ed8.jpg)

Also, please credit "Freepik" which created the avatars with this link in the blogpost:
http://www.freepik.com/free-vector/people-avatars_761436.htm#term=avatar&page=1&position=1

Good luck!

**Comment by elioqoshi** [comment]
P;S: I followed up with Emma via PM and she was happy with these results, hence I closed this right off (in case anyone wonders why I didn't wait for feedback)

**Comment by emmairwin** [comment]
Than you thank you!!

**Comment by elioqoshi** [comment]
Changed Volunteers to Contributors as requested :)
![mozfest cfp images-01](https://cloud.githubusercontent.com/assets/5436686/15689155/f7ddf52a-277d-11e6-94d0-a7ca69202e77.jpg)
![Uploading MozFest CfP Images-02.jpg…]()
