### ISSUE TITLE
Firefox Student Ambassador rollup banner

### ISSUE THREAD

**Issue by ariestiyansyah** [mozilla/Community-Design#9]
Rollup banner design for FSA Program (PNG, PSD, SVG)

Dimension: 76.2cm x 152.4cm

**Comment by elioqoshi** [comment]
Hey @ariestinyansyah , do you need any text on this, or just general FSA?

**Comment by ariestiyansyah** [comment]
Just general FSA

**Comment by elioqoshi** [comment]
Hey @ariestiyansyah here we go:
http://elioqoshi.me/owncloud/index.php/s/Om05cZHdIN61wxx

![76 2x152 4cm-01](https://cloud.githubusercontent.com/assets/5436686/12390641/2271c010-bde2-11e5-9eac-18ee09db20b1.jpg)

**Comment by LucyeoH** [comment]
BEAUTIFUL!

**Comment by ariestiyansyah** [comment]
Awesome @elioqoshi all FSA around the world can use it
